Simple word2vec model with 200 features for each utterance, not considering other features (speaker etc.)

Doc2Vec model for all chats

In [3]:
import os
import json
import gensim

# path = r"C:\Users\user\git\NLPProj\Frames-dataset\chats"


def build_label_dict():
    d = {}
    label_path = r"/home/amirgilad/Documents/git/NLPProj/Frames-dataset/labels.txt"
    label_file = open(label_path, encoding='utf-8')
    for line in label_file:
        k, v = line.split("\t")
        d[k] = v.strip()
    return d

def gen_chat_model(label_dict):
    chat_path = r"/home/amirgilad/Documents/git/NLPProj/Frames-dataset/chats"
    chats = []
    avg_chat_len = 0
    for filename in os.listdir(chat_path):
        chat_file = open(os.path.join(chat_path, filename), encoding='utf-8')
        chat = json.load(chat_file)
        sents = [] # chat level docs
        if 'turns' in chat:
            for turn in chat['turns']:
                sents.extend( turn['text'].split() )
                avg_chat_len += 1
        tagged_chat = gensim.models.doc2vec.TaggedDocument(sents, label_dict[filename])
        chats.append( tagged_chat )
    avg_chat_len /= len(chats)
    print("average number of sents in chat: " + str(avg_chat_len))
    return gensim.models.Doc2Vec(chats, size=100, window=8, min_count=1, workers=4)

# d = build_label_dict()
# chat_model = gen_chat_model(d)

Prepare input vectors from first parts of chats and labels from dictionary

In [4]:
def infer_vectors(chat_model, label_dict, num_of_sents_from_start):
    '''infer vectors for every first part in the chats. 
    Will be used to load the training data and tags'''
    chat_path = r"/home/amirgilad/Documents/git/NLPProj/Frames-dataset/chats"
    chats_vecs = []
    labels = []
    for filename in os.listdir(chat_path):
        chat_file = open(os.path.join(chat_path, filename), encoding='utf-8')
        chat = json.load(chat_file)
        sents = [] # chat level docs
        if 'turns' in chat:
            lim = min(num_of_sents_from_start, len(chat['turns']))
            for i in range( lim ):
                sents.extend( chat['turns'][i]['text'].split() )
#             for turn in chat['turns']:
#                 sents.extend( turn['text'].split() )
        sent_vec = chat_model.infer_vector( sents )
        chats_vecs.append( sent_vec )
        labels.append(label_dict[filename])
    return np.array(chats_vecs), np.array(labels)

Prepare input vectors for all sents in the first parts of chats and labels from dictionary

In [24]:
def infer_vectors_every_sentence(chat_model, label_dict, num_of_sents_from_start):
    '''infer vectors for every first part in the chats. 
    Will be used to load the training data and tags'''
    chat_path = r"/home/amirgilad/Documents/git/NLPProj/Frames-dataset/chats"
    chats_vecs = []
    labels = []
    for filename in os.listdir(chat_path):
        chat_file = open(os.path.join(chat_path, filename), encoding='utf-8')
        chat = json.load(chat_file)
        sents = [] # chat level docs
        if 'turns' in chat:
            lim = min(num_of_sents_from_start, len(chat['turns']))
            for i in range( lim ):
                sents.append( chat_model.infer_vector([chat['turns'][i]['author']] + chat['turns'][i]['text'].split()) )
            if lim < num_of_sents_from_start:
                diff = num_of_sents_from_start - lim
                lst = [chat_model.infer_vector(chat['turns'][-1]['text'].split()) for i in range(diff)]
                sents.extend( lst )
        chats_vecs.append( sents )
        labels.append(label_dict[filename])
    return np.array(chats_vecs), np.array(labels)

One-hot model for words

In [ ]:
def gen_one_hot_dict():
    chat_path = r"/home/amirgilad/Documents/git/NLPProj/Frames-dataset/chats"
    index_dict = {}
    i = 0
    for filename in os.listdir(chat_path):
        chat_file = open(os.path.join(chat_path, filename), encoding='utf-8')
        chat = json.load(chat_file)
        if 'turns' in chat:
            for turn in chat['turns']:
                for word in turn['text'].split():
                    if word.strip() not in index_dict:
                        index_dict[word.strip()] = i
                        i += 1
    return index_dict

def infer_vectors_from_one_hot(index_dict, label_dict, num_of_sents_from_start):
    '''infer vectors for every sentence in the chats. 
    Will be used to load the training data and tags'''
    chat_path = r"/home/amirgilad/Documents/git/NLPProj/Frames-dataset/chats"
    chats_vecs = []
    for filename in os.listdir(chat_path):
        chat_file = open(os.path.join(chat_path, filename), encoding='utf-8')
        chat = json.load(chat_file)
        sents = [] # chat level docs
        if 'turns' in chat:
            lim = min(num_of_sents_from_start, len(chat['turns']))
            for i in range( lim ):
                sents.extend( [index_dict[word.strip()] for word in chat['turns'][i]['text'].split()] )
                
        sent_vec = 
        chats_vecs.append( sent_vec )
        labels.append(label_dict[filename])
    return np.array(chats_vecs), np.array(labels)

Simple LSTM network - does not perform well

In [199]:
import numpy as np
from keras.layers import Input, Dense, merge, Embedding, RNN
from keras.models import Model
import keras
import sys
# should change to relative import
sys.path.insert(0, '/home/amirgilad/Documents/git/NLPProj/kerasAttention')
import attention_dense
import attention_lstm

input_dims = x_train.shape
train_size = 1000

# Build doc2Vec model for the chats
d = build_label_dict()
chat_model = gen_chat_model(d)

# Load the data for the train and test
# The last param is the num. of rows we take from the begining of the chat
num_of_rows_from_start_of_chat = 6
X, Y = infer_vectors(chat_model, d, num_of_rows_from_start_of_chat)

# Divide into training and test data
x_train, y_train = X[:train_size], Y[:train_size]
x_test, y_test = X[train_size:], Y[train_size:]


# Define the model
model = Sequential()
# model.add(Dense(80, input_dim=100, activation='relu'))
input_layer = Dense(80, input_dim=100, activation='relu')

# one attention layer
# attention_probs = Dense(100, activation='softmax', name='attention_probs')(input_layer)
# attention_mul = merge([input_layer, attention_probs], output_shape=(80,), name='attention_mul', mode='mul')
# model.add(attention_mul)
# model.add(input_layer)
# model.add(Dense(60, activation='relu'))
model.add(Embedding(100, 128))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2)) # recurrent
model.add(Dense(64, activation='softmax', name='attention_probs'))
model.add(Dense(1, activation='sigmoid'))

# Compile and fit
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=100, batch_size=32)

# Test the model
scores = model.evaluate(x_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

average number of sents in chat: 14.598977355734112
Epoch 1/100
1000/1000 [==============================] - 10s - loss: 0.6827 - acc: 0.5760    
Epoch 2/100
1000/1000 [==============================] - 9s - loss: 0.6701 - acc: 0.6140     
Epoch 3/100
1000/1000 [==============================] - 9s - loss: 0.6683 - acc: 0.6140     
Epoch 4/100
1000/1000 [==============================] - 10s - loss: 0.6679 - acc: 0.6140    
Epoch 5/100
1000/1000 [==============================] - 9s - loss: 0.6676 - acc: 0.6140     
Epoch 6/100
1000/1000 [==============================] - 9s - loss: 0.6673 - acc: 0.6140     
Epoch 7/100
1000/1000 [==============================] - 9s - loss: 0.6673 - acc: 0.6140     
Epoch 8/100
1000/1000 [==============================] - 10s - loss: 0.6671 - acc: 0.6140    
Epoch 9/100
1000/1000 [==============================] - 10s - loss: 0.6670 - acc: 0.6140    
Epoch 10/100
1000/1000 [==============================] - 10s - loss: 0.6670 - acc: 0.6140    
Epoch 1

RNN network with attention - does not perform well currently

In [210]:
import numpy as np
from keras import layers
from keras.layers import Input, Dense, merge, Embedding, recurrent
from keras.models import Model
import keras
import sys
# should change to relative import
sys.path.insert(0, '/home/amirgilad/Documents/git/NLPProj/kerasAttention')
import attention_dense
import attention_lstm

input_dims = x_train.shape
train_size = 1000

# Build doc2Vec model for the chats
d = build_label_dict()
chat_model = gen_chat_model(d)

# Load the data for the train and test
# The last param is the num. of rows we take from the begining of the chat
num_of_rows_from_start_of_chat = 6
X, Y = infer_vectors(chat_model, d, num_of_rows_from_start_of_chat)

# Divide into training and test data
x_train, y_train = X[:train_size], Y[:train_size]
x_test, y_test = X[train_size:], Y[train_size:]



# model = Sequential()
# # model.add(Dense(80, input_dim=100, activation='relu'))
# input_layer = Dense(80, input_dim=100, activation='relu')


RNN = recurrent.LSTM
EMBED_HIDDEN_SIZE = 100
SENT_HIDDEN_SIZE = 100
BATCH_SIZE = 32
EPOCHS = 40

# Define the model
sentence = Input(shape=(input_dims[1],), dtype='int32')
encoded_sentence = Embedding(100, EMBED_HIDDEN_SIZE)(sentence)
encoded_sentence = layers.Dropout(0.3)(encoded_sentence)
attention_probs = Dense(100, activation='softmax', name='attention_probs')(encoded_sentence)# one attention layer


merged = layers.add([encoded_sentence, attention_probs])
merged = RNN(EMBED_HIDDEN_SIZE)(merged)
merged = layers.Dropout(0.3)(merged)
preds = Dense(1, activation='sigmoid')(merged)

model = Model([sentence], preds)
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

print('Training')
model.fit([x_train], y_train,
          batch_size=BATCH_SIZE,
          epochs=EPOCHS,
          validation_split=0.05)
loss, acc = model.evaluate([x_test], y_test,
                           batch_size=BATCH_SIZE)

print('\nTest loss / test accuracy = {:.4f} / {:.4f}'.format(loss, acc))

average number of sents in chat: 14.598977355734112
Training
Train on 950 samples, validate on 50 samples
Epoch 1/40
950/950 [==============================] - 6s - loss: 0.6687 - acc: 0.6137 - val_loss: 0.7034 - val_acc: 0.5400 loss: 0.6745 - ac
Epoch 2/40
950/950 [==============================] - 6s - loss: 0.6673 - acc: 0.6179 - val_loss: 0.6933 - val_acc: 0.5400
Epoch 3/40
950/950 [==============================] - 7s - loss: 0.6710 - acc: 0.6179 - val_loss: 0.6932 - val_acc: 0.5400
Epoch 4/40
950/950 [==============================] - 7s - loss: 0.6690 - acc: 0.6179 - val_loss: 0.7068 - val_acc: 0.5400
Epoch 5/40
950/950 [==============================] - 7s - loss: 0.6668 - acc: 0.6179 - val_loss: 0.7021 - val_acc: 0.5400
Epoch 6/40
950/950 [==============================] - 7s - loss: 0.6653 - acc: 0.6179 - val_loss: 0.6973 - val_acc: 0.5400
Epoch 7/40
950/950 [==============================] - 7s - loss: 0.6675 - acc: 0.6179 - val_loss: 0.6959 - val_acc: 0.5400
Epoch 8/40
950/

In [25]:
import numpy as np
from keras.layers import merge
from keras.layers.core import *
from keras.layers.recurrent import LSTM
from keras.models import *
import sys
sys.path.insert(0, '/home/amirgilad/Documents/git/NLPProj/kerasAttention')
from attention_utils import get_activations, get_data_recurrent


# Build doc2Vec model for the chats
d = build_label_dict()
chat_model = gen_chat_model(d)

train_size = 1000
batch_size = 50
INPUT_DIM = 100
TIME_STEPS = 6
# if True, the attention vector is shared across the input_dimensions where the attention is applied.
SINGLE_ATTENTION_VECTOR = False
APPLY_ATTENTION_BEFORE_LSTM = False


# Load the data for the train and test
# The last param is the num. of rows we take from the begining of the chat
num_of_rows_from_start_of_chat = TIME_STEPS
X, Y = infer_vectors_every_sentence(chat_model, d, num_of_rows_from_start_of_chat)

# Divide into training and test data
x_train, y_train = X[:train_size], Y[:train_size]
x_test, y_test = X[train_size:], Y[train_size:]

def get_data_recurrent(n, time_steps, input_dim, attention_column=10):
    """
    Data generation. x is purely random except that it's first value equals the target y.
    In practice, the network should learn that the target = x[attention_column].
    Therefore, most of its attention should be focused on the value addressed by attention_column.
    :param n: the number of samples to retrieve.
    :param time_steps: the number of time steps of your series.
    :param input_dim: the number of dimensions of each element in the series.
    :param attention_column: the column linked to the target. Everything else is purely random.
    :return: x: model inputs, y: model targets
    """
#     x = np.random.standard_normal(size=(n, time_steps, input_dim))
    
    sampler = np.random.choice(train_size, batch_size)
    x = x_train[sampler, :num_of_rows_from_start_of_chat, :input_dim]
#     y = np.random.randint(low=0, high=2, size=(n, 1))
    y = y_train[sampler]
#     x[:, attention_column, :] = np.tile(y[:], (1, input_dim))
    return x, y

def attention_3d_block(inputs):
    # inputs.shape = (batch_size, time_steps, input_dim)
#     print(inputs.shape)
    input_dim = INPUT_DIM#int(inputs.shape[2])
    a = Permute((2, 1))(inputs)
    a = Reshape((input_dim, TIME_STEPS))(a)
    a = Dense(TIME_STEPS, activation='softmax')(a)
    if SINGLE_ATTENTION_VECTOR:
        a = Lambda(lambda x: K.mean(x, axis=1), name='dim_reduction')(a)
        a = RepeatVector(input_dim)(a)
    a_probs = Permute((2, 1), name='attention_vec')(a)
    output_attention_mul = merge([inputs, a_probs], name='attention_mul', mode='mul')
#     printoutput_attention_mul.shape
    return output_attention_mul


def model_attention_applied_after_lstm():
    inputs = Input(shape=(TIME_STEPS, INPUT_DIM,))
    lstm_units = 32
    lstm_out = LSTM(lstm_units, return_sequences=True)(inputs)
    attention_mul = attention_3d_block(lstm_out)
    attention_mul = Flatten()(attention_mul)
    output = Dense(1, activation='sigmoid')(attention_mul)
    model = Model(input=[inputs], output=output)
    return model


def model_attention_applied_before_lstm():
    inputs = Input(shape=(TIME_STEPS, INPUT_DIM,))
    attention_mul = attention_3d_block(inputs)
    lstm_units = 32
    attention_mul = LSTM(lstm_units, return_sequences=False)(attention_mul)
    output = Dense(1, activation='sigmoid')(attention_mul)
    model = Model(input=[inputs], output=output)
    return model

N = 1369
# N = 300 -> too few = no training
inputs_1, outputs = get_data_recurrent(N, TIME_STEPS, INPUT_DIM)

# if APPLY_ATTENTION_BEFORE_LSTM:
#     m = model_attention_applied_after_lstm()
# else:
m = model_attention_applied_before_lstm()

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

m.fit([inputs_1], outputs, epochs=1, batch_size=64, validation_split=0.1)

attention_vectors = []
for i in range(300):
    testing_inputs_1, testing_outputs = get_data_recurrent(batch_size, TIME_STEPS, INPUT_DIM)
    attention_vector = np.mean(get_activations(m,
                                               testing_inputs_1,
                                               print_shape_only=True,
                                               layer_name='attention_vec')[0], axis=2).squeeze()
    print('attention =', attention_vector)
    print(np.sum(attention_vector) - 1.0)
#     assert (np.sum(attention_vector) - 1.0) < 1e-5
    attention_vectors.append(attention_vector)

attention_vector_final = np.mean(np.array(attention_vectors), axis=0)


loss, acc = m.evaluate([x_test], y_test,
                           batch_size=batch_size)

print('\nTest loss / test accuracy = {:.4f} / {:.4f}'.format(loss, acc))

# plot part.
# import matplotlib.pyplot as plt
# import pandas as pd

# pd.DataFrame(attention_vector_final, columns=['attention (%)']).plot(kind='bar',
#                                                                      title='Attention Mechanism as '
#                                                                            'a function of input'
#                                                                            ' dimensions.')
# plt.show()

average number of sents in chat: 14.598977355734112


/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:64: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
/usr/local/lib/python3.4/dist-packages/keras/legacy/layers.py:460: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
/usr/local/lib/python3.4/dist-packages/ipykernel_launcher.py:86: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[permute_3..., outputs=sigmoid.0)`


____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_11 (InputLayer)            (None, 6, 100)        0                                            
____________________________________________________________________________________________________
permute_10 (Permute)             (None, 100, 6)        0           input_11[0][0]                   
____________________________________________________________________________________________________
reshape_8 (Reshape)              (None, 100, 6)        0           permute_10[0][0]                 
____________________________________________________________________________________________________
dense_14 (Dense)                 (None, 100, 6)        42          reshape_8[0][0]                  
___________________________________________________________________________________________

(50, 6, 100)
attention = [[ 0.16720635  0.16657749  0.1670389   0.16655587  0.16622449  0.16639687]
 [ 0.16719647  0.16644309  0.16654545  0.16667205  0.16629142  0.16685152]
 [ 0.16719702  0.16652983  0.16655849  0.16587685  0.16626751  0.16757025]
 [ 0.16698544  0.16635118  0.16660017  0.16694395  0.16667034  0.16644898]
 [ 0.16877231  0.16541973  0.16762619  0.16579594  0.16635041  0.16603538]
 [ 0.16708836  0.166501    0.16667978  0.16643368  0.16678551  0.16651168]
 [ 0.1671039   0.16627221  0.16668478  0.16694443  0.16657454  0.16642018]
 [ 0.16770436  0.16630058  0.1671374   0.16523103  0.16615447  0.16747209]
 [ 0.1668022   0.16652279  0.16624574  0.16714975  0.16687727  0.16640222]
 [ 0.16698427  0.16676342  0.16713062  0.16636871  0.16613339  0.16661963]
 [ 0.16671734  0.16689137  0.16699396  0.16642654  0.16661929  0.16635153]
 [ 0.16693717  0.16624759  0.16621149  0.16663794  0.16697706  0.16698879]
 [ 0.16693571  0.16671024  0.16686782  0.16639489  0.16657682  0.16651444]


(50, 6, 100)
attention = [[ 0.16720064  0.16638948  0.16652675  0.1664422   0.16654602  0.16689491]
 [ 0.16692939  0.16660689  0.16669929  0.16660005  0.16625327  0.16691098]
 [ 0.16738982  0.16611439  0.16622898  0.16688164  0.16615404  0.1672311 ]
 [ 0.167881    0.16573876  0.1663945   0.16646291  0.16728938  0.16623341]
 [ 0.16738692  0.16624342  0.16683707  0.16653469  0.16626965  0.16672824]
 [ 0.16635782  0.16703185  0.1669738   0.16721591  0.166537    0.16588363]
 [ 0.16777636  0.16572721  0.16637243  0.16681431  0.16638659  0.16692309]
 [ 0.16728733  0.16639692  0.16695942  0.16707449  0.16637385  0.1659079 ]
 [ 0.1674435   0.16620842  0.16653115  0.16639112  0.16665855  0.1667673 ]
 [ 0.16759293  0.16612028  0.16693041  0.16604544  0.16637549  0.16693552]
 [ 0.1676804   0.16595767  0.16706541  0.16656609  0.16597107  0.1667593 ]
 [ 0.16655068  0.16671444  0.16649103  0.1667973   0.16705431  0.16639231]
 [ 0.16734022  0.16669799  0.16733015  0.16586     0.16588306  0.16688854]


(50, 6, 100)
attention = [[ 0.1672896   0.1662198   0.16682726  0.16620818  0.16683722  0.16661786]
 [ 0.16718192  0.16639221  0.16663381  0.16645861  0.16695331  0.16638015]
 [ 0.16697039  0.16662747  0.16707902  0.16634226  0.16634971  0.16663116]
 [ 0.16663468  0.16648756  0.1663738   0.16674022  0.16700836  0.16675527]
 [ 0.16692856  0.16653129  0.16625372  0.16653553  0.16712052  0.16663028]
 [ 0.16709453  0.16645038  0.16663378  0.16647714  0.1666088   0.16673537]
 [ 0.16728787  0.16600223  0.1660604   0.16659731  0.1670894   0.16696277]
 [ 0.16670001  0.16682605  0.16670023  0.16680586  0.16626501  0.16670288]
 [ 0.16697641  0.16659442  0.16675465  0.16697156  0.16630295  0.16640013]
 [ 0.16684988  0.16648601  0.16623393  0.16737571  0.16704401  0.16601044]
 [ 0.16681391  0.16702756  0.16715491  0.16666529  0.16558304  0.16675527]
 [ 0.16715772  0.16633217  0.16650583  0.16657412  0.16631529  0.16711478]
 [ 0.16705661  0.16633299  0.16666794  0.16642159  0.16688783  0.16663307]


(50, 6, 100)
attention = [[ 0.16702166  0.16664714  0.16632515  0.16651535  0.16675836  0.16673243]
 [ 0.16741902  0.16615048  0.16621618  0.1660911   0.16694634  0.16717692]
 [ 0.16681391  0.16686305  0.16676493  0.16629055  0.16658056  0.16668694]
 [ 0.1671467   0.16658597  0.16720226  0.16621815  0.16612746  0.16671944]
 [ 0.16698362  0.16649662  0.16653013  0.16733204  0.16674639  0.16591124]
 [ 0.16674881  0.16661583  0.16587572  0.16712241  0.16676305  0.16687413]
 [ 0.1663539   0.16729945  0.16684812  0.1668324   0.16635369  0.16631261]
 [ 0.16721982  0.1663764   0.16648723  0.16646738  0.16565862  0.16779055]
 [ 0.16733342  0.16629152  0.16690977  0.1662607   0.16636725  0.16683735]
 [ 0.16733342  0.16629152  0.16690977  0.1662607   0.16636725  0.16683735]
 [ 0.16663195  0.1668687   0.16652264  0.16693252  0.16656061  0.16648354]
 [ 0.16735007  0.1664473   0.16670944  0.16645485  0.16625889  0.16677932]
 [ 0.16674881  0.16661583  0.16587572  0.16712241  0.16676305  0.16687413]


(50, 6, 100)
attention = [[ 0.16701755  0.16631815  0.16605364  0.16685146  0.16713612  0.16662312]
 [ 0.16652218  0.16678368  0.16650075  0.16720806  0.16634068  0.16664477]
 [ 0.16718334  0.16637959  0.16631114  0.16594616  0.16677004  0.16740967]
 [ 0.16642183  0.16677754  0.16618294  0.16750199  0.166687    0.16642876]
 [ 0.16714531  0.16644275  0.16658492  0.16663118  0.1673695   0.16582641]
 [ 0.16740119  0.1662354   0.16703914  0.16618368  0.16648597  0.16665453]
 [ 0.16638075  0.16704416  0.16683519  0.16713442  0.16625029  0.16635518]
 [ 0.1669157   0.16635644  0.16653568  0.16685334  0.16675629  0.1665826 ]
 [ 0.16654097  0.16690166  0.16688265  0.16724744  0.16631199  0.16611527]
 [ 0.16717631  0.1663086   0.16616169  0.16641854  0.16727889  0.16665597]
 [ 0.16717924  0.16631514  0.16657208  0.16629171  0.16633411  0.16730772]
 [ 0.16721745  0.16640508  0.16690454  0.16662464  0.16632681  0.16652149]
 [ 0.16724472  0.16661276  0.16692048  0.16652548  0.1662211   0.16647549]


(50, 6, 100)
attention = [[ 0.16691753  0.16696145  0.16704023  0.16649683  0.16597699  0.16660704]
 [ 0.16743582  0.16590978  0.16642714  0.16578537  0.16745436  0.16698749]
 [ 0.16758221  0.16606846  0.16678183  0.16615561  0.16671269  0.16669922]
 [ 0.16710921  0.16627108  0.16675651  0.16686589  0.16613601  0.16686136]
 [ 0.16709077  0.16610128  0.16606581  0.1668945   0.1669731   0.16687456]
 [ 0.16712879  0.16671765  0.16668612  0.1659354   0.16636196  0.16717003]
 [ 0.16716635  0.16645677  0.16641618  0.1667874   0.16713932  0.16603403]
 [ 0.16766457  0.16582625  0.16679421  0.16574024  0.16677412  0.16720061]
 [ 0.16676925  0.16698512  0.166921    0.16668186  0.16626772  0.16637497]
 [ 0.16710798  0.16646543  0.16686092  0.16659772  0.16629089  0.16667698]
 [ 0.16683383  0.16684131  0.16732344  0.16717944  0.16584104  0.16598094]
 [ 0.16720608  0.16640314  0.16688938  0.16631147  0.16639841  0.16679145]
 [ 0.16659008  0.1669533   0.16641758  0.16664368  0.16676441  0.16663088]


(50, 6, 100)
attention = [[ 0.16659035  0.16663301  0.16616884  0.1673499   0.16639853  0.16685934]
 [ 0.16633205  0.16692084  0.16642857  0.1675638   0.16685206  0.16590273]
 [ 0.16696978  0.16625893  0.16596693  0.16751839  0.16734178  0.16594416]
 [ 0.16714813  0.16629782  0.16629772  0.16729933  0.167033    0.16592398]
 [ 0.16697779  0.166409    0.16646762  0.16653089  0.16691343  0.16670127]
 [ 0.16703719  0.16631453  0.1664537   0.16677313  0.16676332  0.16665815]
 [ 0.16754904  0.16630518  0.16721509  0.16585304  0.16592282  0.16715486]
 [ 0.16706412  0.16621286  0.16636214  0.16710299  0.16671246  0.16654544]
 [ 0.16698261  0.16651133  0.16661738  0.16641378  0.1657864   0.16768838]
 [ 0.16722412  0.16632216  0.16674814  0.16629042  0.16619664  0.16721846]
 [ 0.16631196  0.16739172  0.16684766  0.16705431  0.16639253  0.1660018 ]
 [ 0.16696823  0.16685118  0.16671142  0.16599017  0.16578175  0.16769722]
 [ 0.16685863  0.16641946  0.16634916  0.1670616   0.16701254  0.16629861]


(50, 6, 100)
attention = [[ 0.16751975  0.16594546  0.16659123  0.16588946  0.16673155  0.16732258]
 [ 0.16659117  0.16655202  0.16590841  0.16714333  0.16717851  0.16662653]
 [ 0.16681793  0.16677658  0.16643074  0.16642204  0.16682167  0.16673101]
 [ 0.16686018  0.16686873  0.16714148  0.16650924  0.16608836  0.16653204]
 [ 0.16710746  0.16665533  0.16711235  0.16616854  0.16591172  0.16704457]
 [ 0.16715944  0.166364    0.16665441  0.16661158  0.16689259  0.16631792]
 [ 0.16705661  0.16633299  0.16666794  0.16642159  0.16688783  0.16663307]
 [ 0.16686016  0.16634187  0.16648561  0.16703893  0.16632712  0.16694629]
 [ 0.16690411  0.16646042  0.16645677  0.16641489  0.16678312  0.16698079]
 [ 0.1674435   0.16620842  0.16653115  0.16639112  0.16665855  0.1667673 ]
 [ 0.16715559  0.16645144  0.16675322  0.16625269  0.16662741  0.16675963]
 [ 0.16670765  0.16691077  0.16725321  0.16584791  0.16541372  0.16786669]
 [ 0.166649    0.16679886  0.16682734  0.16698816  0.1665601   0.16617647]


(50, 6, 100)
attention = [[ 0.16694213  0.16659811  0.16671754  0.16699333  0.16642679  0.1663221 ]
 [ 0.16735277  0.1665137   0.16730772  0.16595663  0.16604346  0.16682573]
 [ 0.1671022   0.16636072  0.16670363  0.16663031  0.16597715  0.16722599]
 [ 0.16716698  0.16613247  0.16658668  0.16673774  0.16667727  0.1666988 ]
 [ 0.16699585  0.16631626  0.16648251  0.16727048  0.16709012  0.16584483]
 [ 0.16763252  0.16582684  0.16619405  0.16670002  0.16711792  0.16652869]
 [ 0.16684565  0.16671534  0.16642739  0.16680852  0.16681424  0.16638887]
 [ 0.16693236  0.16655241  0.16649312  0.16673468  0.16659087  0.16669659]
 [ 0.16702127  0.16616841  0.16591267  0.16697183  0.16667946  0.1672464 ]
 [ 0.16658241  0.16692542  0.16679925  0.16691679  0.16657774  0.16619839]
 [ 0.16710958  0.16642858  0.16661876  0.1668732   0.16637699  0.16659273]
 [ 0.16740617  0.16628955  0.16673553  0.16602875  0.1662311   0.16730882]
 [ 0.16690017  0.16663647  0.16653031  0.16640039  0.16649589  0.16703694]


(50, 6, 100)
attention = [[ 0.16724817  0.16643995  0.16670179  0.16649546  0.16644309  0.16667145]
 [ 0.16665147  0.16648817  0.16605717  0.16727528  0.16721928  0.16630858]
 [ 0.16747275  0.16621149  0.16640337  0.16636761  0.16689183  0.16665298]
 [ 0.1670402   0.16637212  0.16646363  0.16665868  0.16672197  0.16674341]
 [ 0.16714627  0.16654097  0.16696584  0.1665789   0.1665372   0.16623075]
 [ 0.16719623  0.16629343  0.16690201  0.1665892   0.16665685  0.1663622 ]
 [ 0.16795021  0.16559476  0.16646704  0.16592668  0.16748607  0.16657528]
 [ 0.1671267   0.16648403  0.16689193  0.16674623  0.16662051  0.16613059]
 [ 0.1669445   0.16672994  0.16674839  0.16678308  0.16659245  0.16620159]
 [ 0.16690411  0.16646042  0.16645677  0.16641489  0.16678312  0.16698079]
 [ 0.16731973  0.1662485   0.16670044  0.1665623   0.16593219  0.16723686]
 [ 0.1670294   0.166806    0.16702984  0.16671863  0.16536604  0.16705008]
 [ 0.16739614  0.16625994  0.16706587  0.16651291  0.16631168  0.16645351]


(50, 6, 100)
attention = [[ 0.16648519  0.16700883  0.1668824   0.16678353  0.1660807   0.1667594 ]
 [ 0.16685906  0.16701373  0.16707768  0.1666353   0.16610266  0.16631159]
 [ 0.16686785  0.16683128  0.1674666   0.16729854  0.16547996  0.16605572]
 [ 0.16736519  0.16603427  0.16628477  0.1664415   0.16676591  0.16710831]
 [ 0.16733682  0.16603556  0.16629691  0.16633627  0.16714765  0.16684675]
 [ 0.16683383  0.16684131  0.16732344  0.16717944  0.16584104  0.16598094]
 [ 0.16751985  0.16643563  0.16726434  0.16590185  0.16543178  0.16744663]
 [ 0.167476    0.16566521  0.16574398  0.16683061  0.16730821  0.16697598]
 [ 0.16723856  0.16624095  0.16665307  0.16649517  0.16683613  0.16653612]
 [ 0.16743569  0.16626264  0.16643518  0.16547611  0.16722591  0.1671645 ]
 [ 0.16644816  0.16693835  0.16648768  0.16709082  0.1663266   0.16670839]
 [ 0.16668122  0.16694775  0.16700234  0.16673598  0.16606241  0.16657025]
 [ 0.16747747  0.16615024  0.16659081  0.16610602  0.16673619  0.16693927]


(50, 6, 100)
attention = [[ 0.16685186  0.16660137  0.16669309  0.16695982  0.16670549  0.16618842]
 [ 0.16751975  0.16594546  0.16659123  0.16588946  0.16673155  0.16732258]
 [ 0.16717795  0.16642542  0.16605663  0.16688216  0.16673812  0.16671978]
 [ 0.16645268  0.16704269  0.16664383  0.16737127  0.16627224  0.16621718]
 [ 0.16723856  0.16624095  0.16665307  0.16649517  0.16683613  0.16653612]
 [ 0.167025    0.16669437  0.16691202  0.16649112  0.16614269  0.16673478]
 [ 0.16717924  0.16631514  0.16657208  0.16629171  0.16633411  0.16730772]
 [ 0.16693489  0.16659312  0.16661982  0.16699082  0.16597791  0.16688347]
 [ 0.16686386  0.16680808  0.16729827  0.16674533  0.16597448  0.16631006]
 [ 0.16730507  0.16590482  0.16649073  0.16688515  0.16702682  0.16638751]
 [ 0.1670294   0.166806    0.16702984  0.16671863  0.16536604  0.16705008]
 [ 0.16668111  0.16694711  0.1669139   0.16723768  0.16612218  0.16609798]
 [ 0.16662973  0.1664529   0.16616946  0.1669997   0.16745222  0.16629595]


(50, 6, 100)
attention = [[ 0.16729674  0.16628665  0.16671936  0.16646355  0.16682135  0.16641237]
 [ 0.16609159  0.16708897  0.16606653  0.16747807  0.16685867  0.16641615]
 [ 0.16728878  0.165786    0.16575359  0.16674657  0.16729939  0.16712566]
 [ 0.16751736  0.16617428  0.1666252   0.16623251  0.16594435  0.16750641]
 [ 0.16687344  0.1668137   0.16696705  0.16706124  0.16585863  0.16642605]
 [ 0.16721411  0.16727167  0.16656312  0.16662094  0.1660625   0.16626766]
 [ 0.1666362   0.16664548  0.16642904  0.16730526  0.16692939  0.16605465]
 [ 0.1671858   0.16639745  0.16727482  0.16722114  0.16573857  0.16618229]
 [ 0.16718987  0.16634667  0.16639356  0.16602668  0.16689707  0.16714612]
 [ 0.16693178  0.16596574  0.1655082   0.16655424  0.16755098  0.1674892 ]
 [ 0.16715266  0.16692147  0.16714552  0.16604123  0.16633859  0.16640057]
 [ 0.16674383  0.16691086  0.16685055  0.16640085  0.16638465  0.16670923]
 [ 0.16697243  0.16665216  0.16705492  0.16672391  0.16607885  0.16651772]


(50, 6, 100)
attention = [[ 0.16758583  0.16578785  0.16635138  0.16596386  0.16751187  0.16679919]
 [ 0.1669298   0.16665182  0.1668971   0.16659003  0.16610461  0.16682661]
 [ 0.16734448  0.16585343  0.16622047  0.16739388  0.1664196   0.16676807]
 [ 0.16707344  0.16645437  0.1668826   0.16631868  0.16633007  0.16694094]
 [ 0.16685641  0.16655937  0.16631122  0.16671459  0.16654639  0.16701199]
 [ 0.16797385  0.16605793  0.16710722  0.16553038  0.16592988  0.16740085]
 [ 0.16680703  0.16681468  0.16691868  0.16690683  0.16620594  0.16634685]
 [ 0.1672419   0.16601637  0.16614242  0.166114    0.16754626  0.16693901]
 [ 0.16751975  0.16594546  0.16659123  0.16588946  0.16673155  0.16732258]
 [ 0.16767728  0.16573156  0.16651458  0.16650935  0.16694438  0.16662292]
 [ 0.16731411  0.16616231  0.16675985  0.16668005  0.16635853  0.16672514]
 [ 0.16691753  0.16696145  0.16704023  0.16649683  0.16597699  0.16660704]
 [ 0.16711658  0.16608877  0.16626549  0.16687675  0.16651224  0.16714022]


(50, 6, 100)
attention = [[ 0.16739614  0.16625994  0.16706587  0.16651291  0.16631168  0.16645351]
 [ 0.16714104  0.16654335  0.16696455  0.16607462  0.16620991  0.16706656]
 [ 0.16714627  0.16654097  0.16696584  0.1665789   0.1665372   0.16623075]
 [ 0.16712858  0.1662183   0.16630216  0.16687702  0.16760541  0.16586851]
 [ 0.16705136  0.16648445  0.16672634  0.1665799   0.16648731  0.16667065]
 [ 0.16667548  0.16645709  0.16583483  0.16705669  0.16732888  0.16664709]
 [ 0.16762276  0.16552103  0.16662399  0.16677174  0.16645695  0.16700351]
 [ 0.16698819  0.1663712   0.1667368   0.16695951  0.16674507  0.16619919]
 [ 0.16678458  0.1668182   0.16688475  0.16650343  0.16602039  0.16698866]
 [ 0.16755669  0.16637312  0.16725025  0.16601562  0.16591176  0.16689254]
 [ 0.16778021  0.16603981  0.16661316  0.16631351  0.16642718  0.16682611]
 [ 0.16723856  0.16624095  0.16665307  0.16649517  0.16683613  0.16653612]
 [ 0.16712235  0.1665969   0.16671582  0.16665754  0.16663797  0.16626944]


(50, 6, 100)
attention = [[ 0.16630611  0.16709478  0.16655481  0.16702734  0.16650733  0.16650958]
 [ 0.16735215  0.16624163  0.16651946  0.16589876  0.16703442  0.16695356]
 [ 0.16716057  0.16622747  0.16653594  0.16664322  0.16707821  0.16635461]
 [ 0.16715559  0.16645144  0.16675322  0.16625269  0.16662741  0.16675963]
 [ 0.16716768  0.1659712   0.1661008   0.16710472  0.16741079  0.16624485]
 [ 0.16660859  0.16636378  0.16628778  0.16760164  0.16668952  0.16644871]
 [ 0.1671522   0.16645227  0.16697182  0.16686696  0.16638115  0.16617571]
 [ 0.16795021  0.16559476  0.16646704  0.16592668  0.16748607  0.16657528]
 [ 0.16672699  0.16621834  0.16554084  0.16728726  0.16732082  0.16690561]
 [ 0.16751666  0.16620545  0.16643941  0.16640154  0.16710429  0.16633271]
 [ 0.16692004  0.16660559  0.16679572  0.16669786  0.16601354  0.16696735]
 [ 0.16685303  0.16665886  0.16650586  0.16641174  0.16669615  0.16687432]
 [ 0.16773257  0.16602653  0.16688918  0.16562523  0.16623843  0.1674881 ]


(50, 6, 100)
attention = [[ 0.16665018  0.16688424  0.16656882  0.16695482  0.16676506  0.16617686]
 [ 0.16652216  0.16654977  0.16628376  0.16710433  0.16732599  0.166214  ]
 [ 0.16786474  0.16614825  0.16751254  0.16546214  0.16626987  0.16674246]
 [ 0.16727322  0.16637026  0.16695838  0.16622509  0.16644089  0.16673224]
 [ 0.16684988  0.16648601  0.16623393  0.16737571  0.16704401  0.16601044]
 [ 0.16686018  0.16686873  0.16714148  0.16650924  0.16608836  0.16653204]
 [ 0.16699956  0.1662742   0.16600867  0.16704911  0.16689646  0.16677207]
 [ 0.16703571  0.16591972  0.16595228  0.16622929  0.16781083  0.16705213]
 [ 0.16694894  0.16663794  0.16704607  0.16672456  0.16628002  0.16636255]
 [ 0.16670929  0.16640213  0.1658069   0.16675575  0.16724429  0.16708165]
 [ 0.16720867  0.16573039  0.16596565  0.16645318  0.1670702   0.16757195]
 [ 0.16725099  0.16646262  0.16711338  0.16613701  0.1662651   0.16677092]
 [ 0.16680703  0.16681468  0.16691868  0.16690683  0.16620594  0.16634685]


(50, 6, 100)
attention = [[ 0.1683657   0.16577964  0.16750999  0.16514131  0.16603321  0.16717   ]
 [ 0.16697243  0.16665216  0.16705492  0.16672391  0.16607885  0.16651772]
 [ 0.16727814  0.16628569  0.16669373  0.16625868  0.16671211  0.16677171]
 [ 0.16719702  0.16652983  0.16655849  0.16587685  0.16626751  0.16757025]
 [ 0.16718368  0.1663755   0.16666365  0.16668628  0.16695426  0.16613665]
 [ 0.16686465  0.16661401  0.16653052  0.16658951  0.1665159   0.16688539]
 [ 0.16695412  0.16627388  0.16571379  0.16657844  0.1671554   0.16732435]
 [ 0.16747977  0.1662401   0.16680345  0.16579041  0.16767183  0.16601439]
 [ 0.16713051  0.16647306  0.1667798   0.16672808  0.16618256  0.16670604]
 [ 0.1669883   0.1666321   0.16699867  0.16662055  0.16625822  0.16650209]
 [ 0.16699772  0.16580532  0.16502038  0.16656923  0.16800459  0.16760284]
 [ 0.167881    0.16573876  0.1663945   0.16646291  0.16728938  0.16623341]
 [ 0.16730507  0.16590482  0.16649073  0.16688515  0.16702682  0.16638751]


(50, 6, 100)
attention = [[ 0.16723107  0.16612332  0.16648538  0.16611801  0.16683768  0.16720457]
 [ 0.16751753  0.16615686  0.16649126  0.16603853  0.16718456  0.16661134]
 [ 0.16687359  0.16649157  0.16695933  0.1673387   0.1663781   0.16595884]
 [ 0.16711551  0.16646172  0.16727535  0.16654839  0.16634874  0.16625032]
 [ 0.16667347  0.1667296   0.16669694  0.16675118  0.16682461  0.1663242 ]
 [ 0.16642025  0.1671899   0.16672598  0.16737682  0.16640538  0.16588171]
 [ 0.1671564   0.16647959  0.16660205  0.16642344  0.16628832  0.16705021]
 [ 0.16736662  0.16589691  0.16667598  0.16673945  0.16683389  0.1664872 ]
 [ 0.16699135  0.16629882  0.16641277  0.16684398  0.16681601  0.166637  ]
 [ 0.16767691  0.16619782  0.16736792  0.16633053  0.16595083  0.1664761 ]
 [ 0.16632326  0.16680236  0.16646619  0.167484    0.16706644  0.16585781]
 [ 0.1667906   0.16692318  0.16702184  0.16652094  0.16629344  0.16644993]
 [ 0.16692278  0.16734646  0.16787763  0.16623579  0.16543931  0.16617808]


(50, 6, 100)
attention = [[ 0.16722046  0.16608498  0.16591692  0.16649634  0.16751753  0.16676383]
 [ 0.16698053  0.16655888  0.1673011   0.16697493  0.16581531  0.16636924]
 [ 0.16723856  0.16624095  0.16665307  0.16649517  0.16683613  0.16653612]
 [ 0.16747166  0.16610643  0.16670416  0.16606268  0.16710593  0.16654912]
 [ 0.1673265   0.16637525  0.16653672  0.16616534  0.16592543  0.1676708 ]
 [ 0.16658241  0.16692542  0.16679925  0.16691679  0.16657774  0.16619839]
 [ 0.16750431  0.16605143  0.16710651  0.16702408  0.16583002  0.16648366]
 [ 0.16765371  0.16618992  0.16726208  0.16617694  0.16588505  0.1668323 ]
 [ 0.16713388  0.16680971  0.16727169  0.16663776  0.16573656  0.16641037]
 [ 0.16714551  0.16635174  0.1665144   0.16641465  0.16679682  0.16677687]
 [ 0.16699204  0.16638847  0.16646767  0.16700907  0.16634017  0.16680261]
 [ 0.16683383  0.16684131  0.16732344  0.16717944  0.16584104  0.16598094]
 [ 0.16714533  0.16642177  0.16684656  0.16622455  0.16673402  0.16662784]


(50, 6, 100)
attention = [[ 0.16681391  0.16686305  0.16676493  0.16629055  0.16658056  0.16668694]
 [ 0.16707611  0.16644165  0.16695358  0.16692474  0.16667415  0.16592978]
 [ 0.16740812  0.16621006  0.16731644  0.16576472  0.16515982  0.16814075]
 [ 0.16685954  0.1664198   0.16600432  0.16650942  0.16726434  0.16694264]
 [ 0.16724233  0.16648264  0.16655362  0.1663821   0.16663206  0.16670717]
 [ 0.1669883   0.1666321   0.16699867  0.16662055  0.16625822  0.16650209]
 [ 0.16687672  0.16678256  0.16703197  0.16655348  0.16646011  0.16629511]
 [ 0.16762732  0.16584314  0.16675766  0.16671963  0.16673055  0.16632175]
 [ 0.16753088  0.16621698  0.16686162  0.16639462  0.16679634  0.16619949]
 [ 0.16683483  0.1665765   0.16641711  0.16720062  0.16677977  0.16619122]
 [ 0.16716997  0.16620815  0.16667387  0.16706058  0.16727421  0.16561322]
 [ 0.16742966  0.16558594  0.16583169  0.16612878  0.16728812  0.16773567]
 [ 0.16641349  0.16726133  0.16695774  0.16729553  0.16639002  0.16568191]


(50, 6, 100)
attention = [[ 0.16652207  0.16690058  0.16648655  0.16681784  0.16707401  0.16619892]
 [ 0.1669798   0.16622038  0.16626659  0.16635507  0.16747421  0.16670388]
 [ 0.16662695  0.16694367  0.16701704  0.16650927  0.16607013  0.16683298]
 [ 0.16751666  0.16593914  0.16624901  0.165977    0.167098    0.16722019]
 [ 0.16665018  0.16688424  0.16656882  0.16695482  0.16676506  0.16617686]
 [ 0.16721411  0.16727167  0.16656312  0.16662094  0.1660625   0.16626766]
 [ 0.16676925  0.16698512  0.166921    0.16668186  0.16626772  0.16637497]
 [ 0.16706556  0.16645519  0.16668972  0.16660069  0.16660379  0.1665851 ]
 [ 0.1668736   0.1668462   0.16694646  0.16645826  0.16616115  0.16671433]
 [ 0.16660859  0.16636378  0.16628778  0.16760164  0.16668952  0.16644871]
 [ 0.16739622  0.16613409  0.16670151  0.16598393  0.16666766  0.16711658]
 [ 0.16702127  0.16616841  0.16591267  0.16697183  0.16667946  0.1672464 ]
 [ 0.16713832  0.16650091  0.16650437  0.16683431  0.1666345   0.16638756]


(50, 6, 100)
attention = [[ 0.16700913  0.16629909  0.16629496  0.16659121  0.16677603  0.16702959]
 [ 0.16641349  0.16726133  0.16695774  0.16729553  0.16639002  0.16568191]
 [ 0.16740957  0.16585672  0.16634119  0.16669409  0.16695021  0.16674826]
 [ 0.16686018  0.16686873  0.16714148  0.16650924  0.16608836  0.16653204]
 [ 0.16693056  0.16648458  0.16649151  0.16642326  0.16682769  0.1668424 ]
 [ 0.16749568  0.16611992  0.16633862  0.16586752  0.16733491  0.16684334]
 [ 0.16730386  0.16613072  0.16631705  0.16649994  0.16701111  0.16673733]
 [ 0.16699956  0.1662742   0.16600867  0.16704911  0.16689646  0.16677207]
 [ 0.16728453  0.16628817  0.16679348  0.16624579  0.16648747  0.16690059]
 [ 0.16708462  0.16589993  0.16582477  0.16693252  0.16779704  0.16646113]
 [ 0.16754727  0.16565706  0.16649878  0.16596742  0.16739646  0.1669331 ]
 [ 0.16707745  0.16652435  0.16709594  0.16675863  0.16640131  0.16614233]
 [ 0.16718334  0.16637959  0.16631114  0.16594616  0.16677004  0.16740967]


(50, 6, 100)
attention = [[ 0.167355    0.1665498   0.16708905  0.16611837  0.16559939  0.16728845]
 [ 0.16668122  0.16694775  0.16700234  0.16673598  0.16606241  0.16657025]
 [ 0.16738662  0.16629271  0.16678748  0.16676268  0.16638899  0.16638154]
 [ 0.16682027  0.16674295  0.16640943  0.16699941  0.16651548  0.1665125 ]
 [ 0.16707344  0.16645437  0.1668826   0.16631868  0.16633007  0.16694094]
 [ 0.16741543  0.16617092  0.16665545  0.16700815  0.16665423  0.16609582]
 [ 0.16680378  0.16657811  0.16635399  0.16696911  0.16649041  0.16680464]
 [ 0.16784334  0.16611966  0.16745806  0.16638122  0.16571049  0.16648728]
 [ 0.16691005  0.16669226  0.1665138   0.16659351  0.16680188  0.16648857]
 [ 0.16688366  0.16684641  0.16717558  0.16609688  0.16619344  0.16680393]
 [ 0.16694333  0.16636311  0.16608208  0.16723128  0.16736621  0.166014  ]
 [ 0.1671022   0.16636072  0.16670363  0.16663031  0.16597715  0.16722599]
 [ 0.1669883   0.1666321   0.16699867  0.16662055  0.16625822  0.16650209]


(50, 6, 100)
attention = [[ 0.1663541   0.16720404  0.16671818  0.16724013  0.16667408  0.16580933]
 [ 0.16762276  0.16552103  0.16662399  0.16677174  0.16645695  0.16700351]
 [ 0.16747275  0.16621149  0.16640337  0.16636761  0.16689183  0.16665298]
 [ 0.16648458  0.16704364  0.16714248  0.16668254  0.16612123  0.16652545]
 [ 0.16692521  0.16659166  0.1665408   0.16669239  0.16661711  0.16663291]
 [ 0.16727372  0.16632317  0.1668469   0.16686188  0.16630124  0.16639309]
 [ 0.16727859  0.16623181  0.16612951  0.16679785  0.1668386   0.16672359]
 [ 0.16679248  0.16668554  0.16660386  0.16675603  0.16662829  0.16653372]
 [ 0.16678727  0.16674934  0.16697174  0.16691896  0.16604063  0.16653211]
 [ 0.1668022   0.16652279  0.16624574  0.16714975  0.16687727  0.16640222]
 [ 0.16743073  0.16650991  0.16700134  0.16677715  0.1654302   0.16685061]
 [ 0.16693056  0.16648458  0.16649151  0.16642326  0.16682769  0.1668424 ]
 [ 0.16789103  0.16526993  0.16530597  0.16624874  0.16751029  0.16777405]


(50, 6, 100)
attention = [[ 0.16707633  0.16651857  0.1665483   0.16652985  0.16655982  0.16676717]
 [ 0.16637252  0.16696003  0.16679864  0.16722257  0.16624446  0.16640177]
 [ 0.16729772  0.16613702  0.16607986  0.16680922  0.16758984  0.16608632]
 [ 0.16770436  0.16630058  0.1671374   0.16523103  0.16615447  0.16747209]
 [ 0.16705954  0.16646822  0.16693327  0.16672367  0.1662609   0.16655444]
 [ 0.16681778  0.16663617  0.16654968  0.16684961  0.16685386  0.16629289]
 [ 0.16714762  0.16626301  0.1664999   0.16669892  0.16709356  0.16629702]
 [ 0.16681391  0.16686305  0.16676493  0.16629055  0.16658056  0.16668694]
 [ 0.16739765  0.16575223  0.16544758  0.16693898  0.1678403   0.16662319]
 [ 0.16699956  0.1662742   0.16600867  0.16704911  0.16689646  0.16677207]
 [ 0.16666521  0.16701169  0.1669016   0.16674717  0.1663397   0.16633461]
 [ 0.16711687  0.16640337  0.1667124   0.16675323  0.16684103  0.16617319]
 [ 0.1668655   0.16662599  0.16649565  0.16718394  0.16649839  0.16633049]


(50, 6, 100)
attention = [[ 0.16770436  0.16630058  0.1671374   0.16523103  0.16615447  0.16747209]
 [ 0.16726193  0.16600104  0.16614074  0.1672153   0.16661809  0.16676302]
 [ 0.16650991  0.16696002  0.167108    0.16740444  0.16648717  0.1655305 ]
 [ 0.16721496  0.16669716  0.16748537  0.16637266  0.16515845  0.16707136]
 [ 0.16730948  0.16632682  0.16627502  0.16642886  0.16707586  0.16658382]
 [ 0.16650242  0.1670668   0.16659844  0.16703407  0.16669437  0.1661039 ]
 [ 0.16697641  0.16659442  0.16675465  0.16697156  0.16630295  0.16640013]
 [ 0.16701643  0.1663667   0.16663     0.16675778  0.16704722  0.16618182]
 [ 0.1671467   0.16658597  0.16720226  0.16621815  0.16612746  0.16671944]
 [ 0.16778021  0.16603981  0.16661316  0.16631351  0.16642718  0.16682611]
 [ 0.16720413  0.16621575  0.16662577  0.16665751  0.16663933  0.16665757]
 [ 0.16743326  0.16625541  0.16692659  0.16628428  0.16636558  0.16673496]
 [ 0.16713491  0.16608123  0.16597436  0.16730803  0.16730255  0.16619898]


(50, 6, 100)
attention = [[ 0.16718334  0.16637959  0.16631114  0.16594616  0.16677004  0.16740967]
 [ 0.16674727  0.16685866  0.16693193  0.16681425  0.16532074  0.16732712]
 [ 0.16720545  0.16660078  0.16673349  0.16659966  0.16663867  0.16622187]
 [ 0.1671703   0.16578716  0.16577797  0.16652265  0.16761704  0.16712488]
 [ 0.16699523  0.16613708  0.16631404  0.16695568  0.16658787  0.16701016]
 [ 0.16695914  0.16626216  0.16598859  0.1672049   0.16675209  0.1668331 ]
 [ 0.1677745   0.16601379  0.16668268  0.16549309  0.1666586   0.16737729]
 [ 0.16671741  0.16704008  0.16752976  0.16690893  0.16546197  0.1663419 ]
 [ 0.16721496  0.16669716  0.16748537  0.16637266  0.16515845  0.16707136]
 [ 0.16690969  0.16642974  0.16622144  0.16692966  0.1672385   0.16627093]
 [ 0.1673588   0.16598007  0.16656204  0.16642047  0.16687135  0.16680726]
 [ 0.16688082  0.16638502  0.1662548   0.16746642  0.16725856  0.16575433]
 [ 0.16686983  0.16678286  0.16742501  0.1668362   0.16592559  0.1661606 ]


(50, 6, 100)
attention = [[ 0.16689968  0.16642497  0.16622852  0.16692828  0.1664746   0.16704394]
 [ 0.16710746  0.16665533  0.16711235  0.16616854  0.16591172  0.16704457]
 [ 0.16633558  0.16712943  0.16646923  0.1674578   0.16627432  0.16633372]
 [ 0.16733342  0.16629152  0.16690977  0.1662607   0.16636725  0.16683735]
 [ 0.16657141  0.16698438  0.16686571  0.16686834  0.16569118  0.16701894]
 [ 0.16739587  0.16568738  0.16565037  0.16701932  0.16820265  0.16604444]
 [ 0.16694894  0.16663794  0.16704607  0.16672456  0.16628002  0.16636255]
 [ 0.16691233  0.16627917  0.16621467  0.16674896  0.16771612  0.16612875]
 [ 0.16697827  0.16635877  0.16648516  0.16640159  0.16663723  0.16713898]
 [ 0.16705671  0.16625698  0.16654301  0.16675876  0.16701651  0.16636801]
 [ 0.16722034  0.16669498  0.16689847  0.16618505  0.16604036  0.16696081]
 [ 0.16731513  0.16638224  0.16665308  0.16638823  0.16638222  0.16687913]
 [ 0.16659117  0.16655202  0.16590841  0.16714333  0.16717851  0.16662653]


(50, 6, 100)
attention = [[ 0.1671858   0.16639745  0.16727482  0.16722114  0.16573857  0.16618229]
 [ 0.16734444  0.16657057  0.1673575   0.16598785  0.16627088  0.16646874]
 [ 0.16800573  0.1657352   0.1665042   0.16624872  0.16657625  0.16692984]
 [ 0.16741261  0.16573836  0.16555277  0.16668063  0.16754486  0.16707075]
 [ 0.16677439  0.16665062  0.16639194  0.16710208  0.16684048  0.16624041]
 [ 0.16731973  0.1662485   0.16670044  0.1665623   0.16593219  0.16723686]
 [ 0.1674782   0.16615513  0.1665076   0.16623935  0.1664381   0.16718161]
 [ 0.16692589  0.16670504  0.16661993  0.16636537  0.16631296  0.16707073]
 [ 0.16705793  0.16663341  0.1665929   0.16641077  0.16680457  0.16650048]
 [ 0.16594094  0.16699266  0.16587068  0.1680073   0.16713767  0.16605072]
 [ 0.16720413  0.16621575  0.16662577  0.16665751  0.16663933  0.16665757]
 [ 0.16735913  0.165878    0.16617134  0.16675478  0.1669101   0.16692673]
 [ 0.16671427  0.16682538  0.16702312  0.1670339   0.16655023  0.1658531 ]


(50, 6, 100)
attention = [[ 0.16695765  0.16657466  0.16681461  0.16670077  0.16728361  0.16566868]
 [ 0.16753052  0.16614312  0.16648212  0.16658024  0.16556707  0.16769694]
 [ 0.16784799  0.16568227  0.16653852  0.16604725  0.16690493  0.16697909]
 [ 0.16730948  0.16632682  0.16627502  0.16642886  0.16707586  0.16658382]
 [ 0.16704993  0.16621715  0.16613574  0.16725719  0.16764966  0.1656903 ]
 [ 0.16738456  0.16627108  0.16663577  0.16611643  0.16647324  0.16711883]
 [ 0.16735215  0.16624163  0.16651946  0.16589876  0.16703442  0.16695356]
 [ 0.1675794   0.16583224  0.16614528  0.16604125  0.16712876  0.167273  ]
 [ 0.16775307  0.16560815  0.16594265  0.16604926  0.16755638  0.16709059]
 [ 0.16685863  0.16641946  0.16634916  0.1670616   0.16701254  0.16629861]
 [ 0.1672388   0.16628866  0.16646129  0.16658893  0.16659023  0.1668321 ]
 [ 0.16718805  0.16636615  0.1665965   0.16686611  0.16595833  0.16702476]
 [ 0.16686018  0.16686873  0.16714148  0.16650924  0.16608836  0.16653204]


(50, 6, 100)
attention = [[ 0.16665147  0.16648817  0.16605717  0.16727528  0.16721928  0.16630858]
 [ 0.16712879  0.16671765  0.16668612  0.1659354   0.16636196  0.16717003]
 [ 0.16685888  0.16640888  0.1669541   0.16760355  0.16610175  0.16607279]
 [ 0.16631196  0.16739172  0.16684766  0.16705431  0.16639253  0.1660018 ]
 [ 0.16759244  0.165501    0.16588476  0.16668297  0.16727251  0.16706635]
 [ 0.16751666  0.16593914  0.16624901  0.165977    0.167098    0.16722019]
 [ 0.1674419   0.16624542  0.16640061  0.16644412  0.166122    0.16734599]
 [ 0.16697243  0.16665216  0.16705492  0.16672391  0.16607885  0.16651772]
 [ 0.1670467   0.16657545  0.16663699  0.16640031  0.16641223  0.16692829]
 [ 0.16733032  0.1662202   0.16660255  0.16658659  0.16699487  0.16626535]
 [ 0.16747452  0.16621104  0.16683273  0.16556755  0.16627741  0.16763686]
 [ 0.16699196  0.16644543  0.166508    0.16651194  0.16722172  0.16632099]
 [ 0.16665147  0.16648817  0.16605717  0.16727528  0.16721928  0.16630858]


(50, 6, 100)
attention = [[ 0.16728787  0.16600223  0.1660604   0.16659731  0.1670894   0.16696277]
 [ 0.16671734  0.16689137  0.16699396  0.16642654  0.16661929  0.16635153]
 [ 0.16725515  0.16660863  0.16714355  0.16598313  0.16617484  0.16683476]
 [ 0.1666757   0.16665985  0.16675219  0.16701029  0.16672796  0.16617405]
 [ 0.16751274  0.16595711  0.16634251  0.1660976   0.16682228  0.16726781]
 [ 0.16763252  0.16582684  0.16619405  0.16670002  0.16711792  0.16652869]
 [ 0.16685186  0.16660137  0.16669309  0.16695982  0.16670549  0.16618842]
 [ 0.16755077  0.16586608  0.16615139  0.16651292  0.16704553  0.16687328]
 [ 0.16719702  0.16652983  0.16655849  0.16587685  0.16626751  0.16757025]
 [ 0.16711882  0.16654807  0.16667911  0.16657275  0.16691698  0.16616428]
 [ 0.16645268  0.16704269  0.16664383  0.16737127  0.16627224  0.16621718]
 [ 0.16705766  0.16655573  0.16673318  0.16624354  0.16629271  0.16711719]
 [ 0.16709453  0.16645038  0.16663378  0.16647714  0.1666088   0.16673537]


(50, 6, 100)
attention = [[ 0.16678727  0.16674934  0.16697174  0.16691896  0.16604063  0.16653211]
 [ 0.16760528  0.16630957  0.16657855  0.16640213  0.16647673  0.1666276 ]
 [ 0.16786474  0.16614825  0.16751254  0.16546214  0.16626987  0.16674246]
 [ 0.16686983  0.16678286  0.16742501  0.1668362   0.16592559  0.1661606 ]
 [ 0.16694357  0.16663928  0.16682762  0.16647933  0.16622873  0.16688144]
 [ 0.16722046  0.16608498  0.16591692  0.16649634  0.16751753  0.16676383]
 [ 0.16695486  0.16627872  0.1665712   0.16637141  0.16673879  0.16708508]
 [ 0.1675169   0.1659946   0.16628395  0.1663183   0.16643573  0.16745055]
 [ 0.16739593  0.16627924  0.16695595  0.16634294  0.1665746   0.16645136]
 [ 0.1671627   0.16632184  0.16696331  0.16632733  0.16631556  0.16690923]
 [ 0.16692257  0.16643029  0.16644384  0.16681673  0.16681424  0.16657227]
 [ 0.16680565  0.16693157  0.16689557  0.16730209  0.16587     0.16619518]
 [ 0.16680282  0.16682686  0.16693836  0.16744967  0.16609207  0.16589017]


(50, 6, 100)
attention = [[ 0.16722034  0.16669498  0.16689847  0.16618505  0.16604036  0.16696081]
 [ 0.16791268  0.16567141  0.16643327  0.16661867  0.16693124  0.16643274]
 [ 0.16699295  0.16672863  0.16679278  0.166786    0.16620332  0.16649634]
 [ 0.16664803  0.16639119  0.16591176  0.16715726  0.16736986  0.16652182]
 [ 0.16669291  0.16656391  0.16628258  0.16728485  0.1669203   0.16625546]
 [ 0.16704626  0.166549    0.16653429  0.1662398   0.16656035  0.16707021]
 [ 0.16633205  0.16692084  0.16642857  0.1675638   0.16685206  0.16590273]
 [ 0.16720413  0.16621575  0.16662577  0.16665751  0.16663933  0.16665757]
 [ 0.16741543  0.16617092  0.16665545  0.16700815  0.16665423  0.16609582]
 [ 0.16634732  0.16717218  0.16674635  0.16700619  0.16642487  0.1663031 ]
 [ 0.16691965  0.16667053  0.16636826  0.16664082  0.16702145  0.16637932]
 [ 0.16694123  0.16648304  0.16667718  0.16692017  0.16656888  0.16640948]
 [ 0.16738692  0.16624342  0.16683707  0.16653469  0.16626965  0.16672824]


(50, 6, 100)
attention = [[ 0.16670208  0.16669013  0.16639835  0.1668947   0.16672353  0.16659121]
 [ 0.16750431  0.16605143  0.16710651  0.16702408  0.16583002  0.16648366]
 [ 0.16727859  0.16623181  0.16612951  0.16679785  0.1668386   0.16672359]
 [ 0.1663539   0.16729945  0.16684812  0.1668324   0.16635369  0.16631261]
 [ 0.16748184  0.16615988  0.16628785  0.16668192  0.1665106   0.16687794]
 [ 0.16697641  0.16659442  0.16675465  0.16697156  0.16630295  0.16640013]
 [ 0.16664922  0.16677468  0.16674294  0.16697225  0.16653301  0.16632791]
 [ 0.1674431   0.16618237  0.16657838  0.16654357  0.16679783  0.16645466]
 [ 0.16701755  0.16631815  0.16605364  0.16685146  0.16713612  0.16662312]
 [ 0.16719054  0.16633284  0.16674221  0.16703662  0.16609593  0.16660185]
 [ 0.16645287  0.16690582  0.16664843  0.16726393  0.16639771  0.16633137]
 [ 0.16667347  0.1667296   0.16669694  0.16675118  0.16682461  0.1663242 ]
 [ 0.16720867  0.16573039  0.16596565  0.16645318  0.1670702   0.16757195]


(50, 6, 100)
attention = [[ 0.16680917  0.16648905  0.1665234   0.16742843  0.16593315  0.16681683]
 [ 0.16748217  0.16570188  0.16598046  0.16652374  0.16717538  0.16713631]
 [ 0.16694894  0.16633976  0.16642644  0.16687146  0.16636227  0.16705114]
 [ 0.16718192  0.16639221  0.16663381  0.16645861  0.16695331  0.16638015]
 [ 0.16753052  0.16614312  0.16648212  0.16658024  0.16556707  0.16769694]
 [ 0.16721745  0.16640508  0.16690454  0.16662464  0.16632681  0.16652149]
 [ 0.16674881  0.16661583  0.16587572  0.16712241  0.16676305  0.16687413]
 [ 0.16735931  0.1663534   0.1671567   0.166446    0.16588527  0.16679925]
 [ 0.1672419   0.16601637  0.16614242  0.166114    0.16754626  0.16693901]
 [ 0.16713797  0.1664734   0.16658983  0.16633713  0.16660847  0.16685322]
 [ 0.16675147  0.16660692  0.16654435  0.16734956  0.1667088   0.16603874]
 [ 0.16766457  0.16582625  0.16679421  0.16574024  0.16677412  0.16720061]
 [ 0.16674308  0.16648838  0.16608475  0.16677769  0.16686282  0.16704334]


(50, 6, 100)
attention = [[ 0.16699949  0.16655642  0.16653278  0.16658434  0.16664921  0.16667777]
 [ 0.16771513  0.16628172  0.16745736  0.16648518  0.16523308  0.16682754]
 [ 0.1666297   0.16688988  0.16658483  0.16698864  0.16643502  0.16647187]
 [ 0.16706935  0.16588476  0.16585873  0.16686562  0.16733025  0.16699135]
 [ 0.16727777  0.16632028  0.16686979  0.16660058  0.16631827  0.1666133 ]
 [ 0.16751985  0.16643563  0.16726434  0.16590185  0.16543178  0.16744663]
 [ 0.16709532  0.16666864  0.16668878  0.16633554  0.16675827  0.16645341]
 [ 0.16698362  0.16649662  0.16653013  0.16733204  0.16674639  0.16591124]
 [ 0.16688482  0.16669513  0.16678099  0.16627194  0.16644551  0.16692157]
 [ 0.16686016  0.16634187  0.16648561  0.16703893  0.16632712  0.16694629]
 [ 0.16644816  0.16693835  0.16648768  0.16709082  0.1663266   0.16670839]
 [ 0.1674569   0.16615781  0.16714841  0.16635807  0.1662187   0.16666017]
 [ 0.16767691  0.16619782  0.16736792  0.16633053  0.16595083  0.1664761 ]


(50, 6, 100)
attention = [[ 0.16830172  0.16545336  0.16710514  0.16533914  0.16637005  0.16743065]
 [ 0.16663341  0.16692217  0.16648734  0.16728607  0.16657673  0.16609432]
 [ 0.16708292  0.16629294  0.16584991  0.16674578  0.16721578  0.16681267]
 [ 0.16731513  0.16638224  0.16665308  0.16638823  0.16638222  0.16687913]
 [ 0.16743326  0.16625541  0.16692659  0.16628428  0.16636558  0.16673496]
 [ 0.16682565  0.16625336  0.16640404  0.16740212  0.16716962  0.16594519]
 [ 0.16727777  0.16617379  0.16658193  0.16670051  0.16740133  0.16586468]
 [ 0.16684565  0.16671534  0.16642739  0.16680852  0.16681424  0.16638887]
 [ 0.16688539  0.16633005  0.16671921  0.16739063  0.16634943  0.16632536]
 [ 0.16728467  0.16628475  0.16674811  0.16629723  0.16686493  0.16652042]
 [ 0.16676496  0.16676079  0.16673166  0.16692318  0.16581649  0.16700293]
 [ 0.16717672  0.16632046  0.16668822  0.16631393  0.16697191  0.16652878]
 [ 0.16712068  0.16623384  0.16609402  0.16614573  0.16711697  0.16728872]


(50, 6, 100)
attention = [[ 0.16661105  0.16680636  0.16635492  0.16726896  0.16704293  0.16591577]
 [ 0.16763252  0.16582684  0.16619405  0.16670002  0.16711792  0.16652869]
 [ 0.16711658  0.16608877  0.16626549  0.16687675  0.16651224  0.16714022]
 [ 0.16664635  0.16689309  0.16691673  0.16696481  0.16594319  0.1666358 ]
 [ 0.16713625  0.166384    0.16689795  0.16711466  0.16629565  0.16617146]
 [ 0.1674782   0.16615513  0.1665076   0.16623935  0.1664381   0.16718161]
 [ 0.16700356  0.16635475  0.16621087  0.16674241  0.16733518  0.16635321]
 [ 0.16686359  0.16654241  0.16646026  0.16668777  0.16674055  0.1667054 ]
 [ 0.16757917  0.16561131  0.16579746  0.16666131  0.16749898  0.16685179]
 [ 0.16763252  0.16582684  0.16619405  0.16670002  0.16711792  0.16652869]
 [ 0.16643713  0.16703987  0.16688775  0.16733108  0.16657118  0.16573292]
 [ 0.16731973  0.1662485   0.16670044  0.1665623   0.16593219  0.16723686]
 [ 0.16668111  0.16694711  0.1669139   0.16723768  0.16612218  0.16609798]


(50, 6, 100)
attention = [[ 0.16751666  0.16620545  0.16643941  0.16640154  0.16710429  0.16633271]
 [ 0.16625032  0.16694966  0.16642684  0.16746758  0.16657895  0.1663267 ]
 [ 0.16644993  0.16707125  0.16671078  0.16684315  0.16677487  0.16615002]
 [ 0.16762903  0.16584238  0.16654463  0.16706426  0.16519397  0.1677257 ]
 [ 0.16688654  0.16632652  0.16608918  0.16661589  0.167045    0.16703692]
 [ 0.16638075  0.16704416  0.16683519  0.16713442  0.16625029  0.16635518]
 [ 0.16673613  0.16695736  0.16673243  0.1666458   0.16598588  0.1669424 ]
 [ 0.16745961  0.16647439  0.16702436  0.16651466  0.16520372  0.16732326]
 [ 0.16822864  0.16556726  0.16662169  0.16629526  0.1653285   0.16795866]
 [ 0.16719702  0.16652983  0.16655849  0.16587685  0.16626751  0.16757025]
 [ 0.1674419   0.16624542  0.16640061  0.16644412  0.166122    0.16734599]
 [ 0.16705793  0.16663341  0.1665929   0.16641077  0.16680457  0.16650048]
 [ 0.167025    0.16669437  0.16691202  0.16649112  0.16614269  0.16673478]


(50, 6, 100)
attention = [[ 0.16678181  0.16684593  0.16673175  0.16666843  0.16642159  0.16655049]
 [ 0.16666649  0.16664949  0.16619807  0.16722187  0.16720603  0.16605806]
 [ 0.16671129  0.16643056  0.16590241  0.16705838  0.16728178  0.16661564]
 [ 0.16689824  0.16642338  0.16634545  0.16680735  0.16678721  0.16673844]
 [ 0.16730984  0.16647552  0.1666708   0.16696087  0.16688886  0.1656941 ]
 [ 0.16729772  0.16613702  0.16607986  0.16680922  0.16758984  0.16608632]
 [ 0.16699587  0.16633564  0.16627234  0.16706915  0.16677795  0.16654909]
 [ 0.16691022  0.1666404   0.16648225  0.16630429  0.16654348  0.16711932]
 [ 0.16683383  0.16684131  0.16732344  0.16717944  0.16584104  0.16598094]
 [ 0.16700505  0.16648519  0.16635357  0.1665024   0.16652222  0.16713168]
 [ 0.16714813  0.16629782  0.16629772  0.16729933  0.167033    0.16592398]
 [ 0.16663341  0.16692217  0.16648734  0.16728607  0.16657673  0.16609432]
 [ 0.16686317  0.16666502  0.16659246  0.16661653  0.16668424  0.16657856]


(50, 6, 100)
attention = [[ 0.16639119  0.16658771  0.16563547  0.16690418  0.16797556  0.16650601]
 [ 0.16700356  0.16635475  0.16621087  0.16674241  0.16733518  0.16635321]
 [ 0.1669624   0.16656519  0.16637507  0.16697012  0.16678441  0.16634274]
 [ 0.16644993  0.16707125  0.16671078  0.16684315  0.16677487  0.16615002]
 [ 0.16699295  0.16672863  0.16679278  0.166786    0.16620332  0.16649634]
 [ 0.16654426  0.16685466  0.16658373  0.16749048  0.1667918   0.16573519]
 [ 0.16743073  0.16650991  0.16700134  0.16677715  0.1654302   0.16685061]
 [ 0.167476    0.16566521  0.16574398  0.16683061  0.16730821  0.16697598]
 [ 0.16706841  0.16615975  0.16576278  0.16644207  0.16723986  0.16732714]
 [ 0.16680636  0.16655031  0.16643122  0.16675216  0.16676503  0.16669485]
 [ 0.16720913  0.16625901  0.16631557  0.16675715  0.16659901  0.16686015]
 [ 0.16785574  0.16580799  0.16652428  0.1655964   0.16684268  0.16737296]
 [ 0.16720413  0.16621575  0.16662577  0.16665751  0.16663933  0.16665757]


(50, 6, 100)
attention = [[ 0.16691607  0.16692343  0.16742609  0.16665249  0.16591889  0.16616306]
 [ 0.16710079  0.16641687  0.16660239  0.1669386   0.16678199  0.16615942]
 [ 0.16686261  0.16632183  0.16574293  0.16639274  0.16753167  0.16714837]
 [ 0.16759293  0.16612028  0.16693041  0.16604544  0.16637549  0.16693552]
 [ 0.16720112  0.1662619   0.1661941   0.16701902  0.16685151  0.16647235]
 [ 0.16691549  0.16603537  0.16586475  0.16689487  0.16834532  0.16594422]
 [ 0.16698261  0.16651133  0.16661738  0.16641378  0.1657864   0.16768838]
 [ 0.16688864  0.16658087  0.16652271  0.16674562  0.16696201  0.16630012]
 [ 0.16644241  0.16691655  0.16692679  0.16737288  0.16635269  0.16598871]
 [ 0.16742676  0.16596602  0.16646732  0.16684669  0.16685109  0.1664421 ]
 [ 0.1668655   0.16662599  0.16649565  0.16718394  0.16649839  0.16633049]
 [ 0.16681391  0.16686305  0.16676493  0.16629055  0.16658056  0.16668694]
 [ 0.16708359  0.16643517  0.16689005  0.16682981  0.16684085  0.16592059]


(50, 6, 100)
attention = [[ 0.16738345  0.16643168  0.16705547  0.16590096  0.16631958  0.16690889]
 [ 0.16760412  0.16619465  0.16694693  0.16640759  0.16635127  0.16649546]
 [ 0.16735224  0.16592871  0.16571864  0.1663997   0.16701421  0.1675864 ]
 [ 0.1668011   0.16673906  0.16698743  0.1669593   0.16617723  0.16633585]
 [ 0.16739614  0.16625994  0.16706587  0.16651291  0.16631168  0.16645351]
 [ 0.16669157  0.16676569  0.16636449  0.16684265  0.16704905  0.16628651]
 [ 0.1671136   0.16656461  0.16661024  0.16657194  0.16620693  0.16693257]
 [ 0.16717188  0.1663854   0.16646715  0.16663782  0.16718055  0.16615719]
 [ 0.16760628  0.16597645  0.16656291  0.16665298  0.16676119  0.16644029]
 [ 0.16692521  0.16659166  0.1665408   0.16669239  0.16661711  0.16663291]
 [ 0.16754727  0.16565706  0.16649878  0.16596742  0.16739646  0.1669331 ]
 [ 0.16731513  0.16638224  0.16665308  0.16638823  0.16638222  0.16687913]
 [ 0.16677439  0.16665062  0.16639194  0.16710208  0.16684048  0.16624041]


(50, 6, 100)
attention = [[ 0.16714153  0.16631383  0.1661503   0.16685338  0.16676612  0.16677488]
 [ 0.16668122  0.16694775  0.16700234  0.16673598  0.16606241  0.16657025]
 [ 0.16674489  0.16666918  0.16630867  0.16773944  0.16623005  0.16630785]
 [ 0.16721982  0.1663764   0.16648723  0.16646738  0.16565862  0.16779055]
 [ 0.16710667  0.16635281  0.16642505  0.16695733  0.165887    0.1672712 ]
 [ 0.16644217  0.16673106  0.16613384  0.16724166  0.16730137  0.16614977]
 [ 0.16711551  0.16646172  0.16727535  0.16654839  0.16634874  0.16625032]
 [ 0.16702034  0.16652694  0.16664839  0.1664189   0.16675623  0.16662927]
 [ 0.16699585  0.16631626  0.16648251  0.16727048  0.16709012  0.16584483]
 [ 0.16746707  0.16644962  0.16679102  0.16584487  0.16675831  0.16668904]
 [ 0.16757053  0.16575903  0.16640303  0.16651618  0.16673462  0.16701649]
 [ 0.16746794  0.16592176  0.16626671  0.16632895  0.16722888  0.16678579]
 [ 0.16692591  0.16649307  0.16669674  0.16647534  0.16672464  0.16668424]


(50, 6, 100)
attention = [[ 0.16690147  0.16646788  0.16634069  0.1665118   0.1669389   0.16683918]
 [ 0.16706666  0.16624279  0.16626337  0.16725303  0.16723645  0.16593768]
 [ 0.16690168  0.16640972  0.16630198  0.16665848  0.16696325  0.16676487]
 [ 0.16711801  0.16668074  0.16704953  0.16614369  0.16643552  0.1665725 ]
 [ 0.1671858   0.16639745  0.16727482  0.16722114  0.16573857  0.16618229]
 [ 0.16674308  0.16648838  0.16608475  0.16677769  0.16686282  0.16704334]
 [ 0.16728787  0.16600223  0.1660604   0.16659731  0.1670894   0.16696277]
 [ 0.16692257  0.16643029  0.16644384  0.16681673  0.16681424  0.16657227]
 [ 0.16697827  0.16635877  0.16648516  0.16640159  0.16663723  0.16713898]
 [ 0.16692589  0.16670504  0.16661993  0.16636537  0.16631296  0.16707073]
 [ 0.16699204  0.16638847  0.16646767  0.16700907  0.16634017  0.16680261]
 [ 0.16733584  0.16624545  0.16668493  0.16645487  0.16646793  0.16681091]
 [ 0.16722046  0.16608498  0.16591692  0.16649634  0.16751753  0.16676383]


(50, 6, 100)
attention = [[ 0.16705766  0.16655573  0.16673318  0.16624354  0.16629271  0.16711719]
 [ 0.16693056  0.16648458  0.16649151  0.16642326  0.16682769  0.1668424 ]
 [ 0.16698386  0.1669787   0.16726121  0.16628782  0.16562133  0.16686712]
 [ 0.1675861   0.16592869  0.16619839  0.16664131  0.16757704  0.16606851]
 [ 0.1675169   0.1659946   0.16628395  0.1663183   0.16643573  0.16745055]
 [ 0.16699587  0.16633564  0.16627234  0.16706915  0.16677795  0.16654909]
 [ 0.16746707  0.16644962  0.16679102  0.16584487  0.16675831  0.16668904]
 [ 0.1670294   0.166806    0.16702984  0.16671863  0.16536604  0.16705008]
 [ 0.16739614  0.16625994  0.16706587  0.16651291  0.16631168  0.16645351]
 [ 0.16687344  0.1668137   0.16696705  0.16706124  0.16585863  0.16642605]
 [ 0.16664922  0.16677468  0.16674294  0.16697225  0.16653301  0.16632791]
 [ 0.16699196  0.16644543  0.166508    0.16651194  0.16722172  0.16632099]
 [ 0.16761641  0.16582775  0.16618618  0.16660015  0.16720156  0.16656798]


(50, 6, 100)
attention = [[ 0.16703571  0.16654296  0.16698696  0.16648453  0.16654295  0.16640693]
 [ 0.16699135  0.16629882  0.16641277  0.16684398  0.16681601  0.166637  ]
 [ 0.1669445   0.16672994  0.16674839  0.16678308  0.16659245  0.16620159]
 [ 0.16692521  0.16659166  0.1665408   0.16669239  0.16661711  0.16663291]
 [ 0.1667759   0.16663426  0.16674013  0.16751875  0.16626093  0.16607003]
 [ 0.16760969  0.16624239  0.1667975   0.16640116  0.16613168  0.16681765]
 [ 0.1671847   0.16617569  0.16611983  0.16691925  0.16701213  0.16658844]
 [ 0.16718744  0.16628635  0.16664344  0.16660543  0.16677479  0.16650254]
 [ 0.16680565  0.16693157  0.16689557  0.16730209  0.16587     0.16619518]
 [ 0.167055    0.1663918   0.16623046  0.16673809  0.16692495  0.1666597 ]
 [ 0.16687344  0.1668137   0.16696705  0.16706124  0.16585863  0.16642605]
 [ 0.16739593  0.16627924  0.16695595  0.16634294  0.1665746   0.16645136]
 [ 0.1674419   0.16624542  0.16640061  0.16644412  0.166122    0.16734599]


(50, 6, 100)
attention = [[ 0.16714153  0.16631383  0.1661503   0.16685338  0.16676612  0.16677488]
 [ 0.16711801  0.16628662  0.16633326  0.16709279  0.16693941  0.16622998]
 [ 0.16700658  0.16623379  0.16627899  0.16676158  0.1669129   0.16680616]
 [ 0.16718982  0.16618954  0.16632359  0.16677582  0.1671394   0.16638178]
 [ 0.16724817  0.16643995  0.16670179  0.16649546  0.16644309  0.16667145]
 [ 0.1666297   0.16688988  0.16658483  0.16698864  0.16643502  0.16647187]
 [ 0.16697064  0.16637041  0.16671254  0.16686039  0.16654715  0.16653885]
 [ 0.1674189   0.16616915  0.16668475  0.16627243  0.1669125   0.16654238]
 [ 0.1671564   0.16647959  0.16660205  0.16642344  0.16628832  0.16705021]
 [ 0.16690168  0.16640972  0.16630198  0.16665848  0.16696325  0.16676487]
 [ 0.16716585  0.16612761  0.1663179   0.16727339  0.16706352  0.16605172]
 [ 0.16644217  0.16673106  0.16613384  0.16724166  0.16730137  0.16614977]
 [ 0.1668469   0.16646576  0.16646229  0.16742146  0.16626768  0.16653587]


(50, 6, 100)
attention = [[ 0.16685863  0.16641946  0.16634916  0.1670616   0.16701254  0.16629861]
 [ 0.16669291  0.16656391  0.16628258  0.16728485  0.1669203   0.16625546]
 [ 0.16710947  0.1664218   0.16686778  0.16665266  0.16619903  0.1667493 ]
 [ 0.16726869  0.16599421  0.16579382  0.16649075  0.16776091  0.16669166]
 [ 0.16739593  0.16627924  0.16695595  0.16634294  0.1665746   0.16645136]
 [ 0.16660069  0.16656411  0.16626976  0.16735069  0.16716467  0.16605015]
 [ 0.16709292  0.16620839  0.16634291  0.16629803  0.16686496  0.16719286]
 [ 0.16733584  0.16624545  0.16668493  0.16645487  0.16646793  0.16681091]
 [ 0.16717795  0.16642542  0.16605663  0.16688216  0.16673812  0.16671978]
 [ 0.167881    0.16573876  0.1663945   0.16646291  0.16728938  0.16623341]
 [ 0.16746315  0.16637924  0.16687946  0.16628286  0.16595814  0.16703726]
 [ 0.1674435   0.16620842  0.16653115  0.16639112  0.16665855  0.1667673 ]
 [ 0.167476    0.16566521  0.16574398  0.16683061  0.16730821  0.16697598]


(50, 6, 100)
attention = [[ 0.16715559  0.16645144  0.16675322  0.16625269  0.16662741  0.16675963]
 [ 0.16720413  0.16621575  0.16662577  0.16665751  0.16663933  0.16665757]
 [ 0.16681992  0.16680557  0.16687909  0.16655731  0.16655277  0.16638532]
 [ 0.16739015  0.16614047  0.16676399  0.16656393  0.16665794  0.16648355]
 [ 0.16665147  0.16648817  0.16605717  0.16727528  0.16721928  0.16630858]
 [ 0.16760528  0.16630957  0.16657855  0.16640213  0.16647673  0.1666276 ]
 [ 0.16690017  0.16663647  0.16653031  0.16640039  0.16649589  0.16703694]
 [ 0.16671535  0.16678147  0.16681567  0.1668832   0.1662323   0.16657197]
 [ 0.16743211  0.16639197  0.16701357  0.16598491  0.16557989  0.16759752]
 [ 0.16726194  0.16634466  0.1670562   0.16644511  0.16617127  0.16672087]
 [ 0.16657847  0.16692835  0.16695334  0.16710044  0.1660057   0.16643362]
 [ 0.16753088  0.16621698  0.16686162  0.16639462  0.16679634  0.16619949]
 [ 0.16754279  0.1662638   0.16667961  0.16582718  0.16627489  0.16741167]


(50, 6, 100)
attention = [[ 0.1667906   0.16692318  0.16702184  0.16652094  0.16629344  0.16644993]
 [ 0.16697823  0.16654097  0.16667384  0.16692293  0.16670336  0.16618066]
 [ 0.16698438  0.16679737  0.16691567  0.16672297  0.1662569   0.16632286]
 [ 0.16697039  0.16662747  0.16707902  0.16634226  0.16634971  0.16663116]
 [ 0.16631196  0.16739172  0.16684766  0.16705431  0.16639253  0.1660018 ]
 [ 0.16747208  0.16590065  0.16677037  0.16580358  0.16663677  0.16741662]
 [ 0.16706666  0.16624279  0.16626337  0.16725303  0.16723645  0.16593768]
 [ 0.16681971  0.16661523  0.16683573  0.16678292  0.16663975  0.16630651]
 [ 0.16683483  0.1665765   0.16641711  0.16720062  0.16677977  0.16619122]
 [ 0.16734895  0.16657279  0.16740058  0.16596302  0.16636476  0.16634984]
 [ 0.16726193  0.16600104  0.16614074  0.1672153   0.16661809  0.16676302]
 [ 0.16708611  0.16610831  0.16561836  0.1675349   0.16702656  0.16662575]
 [ 0.167355    0.1665498   0.16708905  0.16611837  0.16559939  0.16728845]


(50, 6, 100)
attention = [[ 0.16693182  0.16649377  0.16603068  0.16706036  0.1671187   0.16636476]
 [ 0.16724892  0.1661869   0.16657764  0.16637722  0.16726039  0.16634887]
 [ 0.1674782   0.16615513  0.1665076   0.16623935  0.1664381   0.16718161]
 [ 0.16720635  0.16657749  0.1670389   0.16655587  0.16622449  0.16639687]
 [ 0.16735519  0.16634518  0.16706066  0.16624208  0.16636328  0.16663365]
 [ 0.16681296  0.16652611  0.16636489  0.16674136  0.16670157  0.16685314]
 [ 0.16710798  0.16646543  0.16686092  0.16659772  0.16629089  0.16667698]
 [ 0.1665986   0.16674162  0.1665644   0.16647863  0.16718359  0.16643313]
 [ 0.16637899  0.16710567  0.16672285  0.16721521  0.16652673  0.16605045]
 [ 0.16696006  0.16677757  0.1668772   0.16668579  0.16625309  0.16644619]
 [ 0.16706935  0.16588476  0.16585873  0.16686562  0.16733025  0.16699135]
 [ 0.16709253  0.16636461  0.16663593  0.16668941  0.16690809  0.1663094 ]
 [ 0.16710438  0.16681826  0.16711576  0.16578007  0.16641846  0.1667631 ]


(50, 6, 100)
attention = [[ 0.16715559  0.16645144  0.16675322  0.16625269  0.16662741  0.16675963]
 [ 0.16755112  0.16592766  0.16640741  0.16644354  0.16670157  0.16696869]
 [ 0.16711551  0.16646172  0.16727535  0.16654839  0.16634874  0.16625032]
 [ 0.1667759   0.16663426  0.16674013  0.16751875  0.16626093  0.16607003]
 [ 0.16720635  0.16657749  0.1670389   0.16655587  0.16622449  0.16639687]
 [ 0.16666365  0.16665125  0.16673361  0.16741331  0.1665042   0.16603392]
 [ 0.16668469  0.16683301  0.16685277  0.16664796  0.16623762  0.16674401]
 [ 0.16750963  0.16596989  0.16642286  0.16676506  0.16616969  0.1671629 ]
 [ 0.16800117  0.16575992  0.16658305  0.16643931  0.16668366  0.16653287]
 [ 0.16688864  0.16658087  0.16652271  0.16674562  0.16696201  0.16630012]
 [ 0.16750202  0.16574296  0.16604008  0.1660479   0.16754551  0.16712156]
 [ 0.16648458  0.16704364  0.16714248  0.16668254  0.16612123  0.16652545]
 [ 0.16730846  0.16602148  0.16592419  0.16673021  0.1678161   0.16619949]


(50, 6, 100)
attention = [[ 0.16683383  0.16684131  0.16732344  0.16717944  0.16584104  0.16598094]
 [ 0.16698362  0.16649662  0.16653013  0.16733204  0.16674639  0.16591124]
 [ 0.16686983  0.16678286  0.16742501  0.1668362   0.16592559  0.1661606 ]
 [ 0.16679704  0.16661121  0.16622742  0.16681829  0.16709574  0.16645025]
 [ 0.16684684  0.16639853  0.16634282  0.16694769  0.16668436  0.1667798 ]
 [ 0.16688082  0.16638502  0.1662548   0.16746642  0.16725856  0.16575433]
 [ 0.16676088  0.16657373  0.16649337  0.16674136  0.16683508  0.16659559]
 [ 0.16655584  0.16697252  0.16626571  0.16674328  0.16711506  0.16634765]
 [ 0.16786474  0.16614825  0.16751254  0.16546214  0.16626987  0.16674246]
 [ 0.16734761  0.16631135  0.16707708  0.16664037  0.16613577  0.16648777]
 [ 0.16702224  0.16637489  0.16639405  0.16660471  0.16694388  0.16666029]
 [ 0.16794892  0.16611351  0.1675705   0.16585098  0.16524592  0.16727018]
 [ 0.16644241  0.16691655  0.16692679  0.16737288  0.16635269  0.16598871]


(50, 6, 100)
attention = [[ 0.16726193  0.16600104  0.16614074  0.1672153   0.16661809  0.16676302]
 [ 0.16738985  0.16628197  0.16668157  0.16656284  0.16669036  0.16639341]
 [ 0.16754727  0.16565706  0.16649878  0.16596742  0.16739646  0.1669331 ]
 [ 0.1671847   0.16617569  0.16611983  0.16691925  0.16701213  0.16658844]
 [ 0.16709286  0.16654928  0.16684049  0.16633052  0.16639541  0.16679148]
 [ 0.16716644  0.16646576  0.16677129  0.16602573  0.16622463  0.16734613]
 [ 0.16712068  0.16623384  0.16609402  0.16614573  0.16711697  0.16728872]
 [ 0.16741417  0.16602495  0.16622531  0.16633013  0.16723883  0.1667666 ]
 [ 0.16675077  0.16667672  0.16708976  0.16702729  0.16656275  0.16589269]
 [ 0.16716616  0.16658527  0.16727865  0.16631317  0.16596861  0.16668811]
 [ 0.16728733  0.16639692  0.16695942  0.16707449  0.16637385  0.1659079 ]
 [ 0.16675024  0.16698191  0.16724561  0.16672811  0.16615446  0.16613965]
 [ 0.16637971  0.16683067  0.16652755  0.16743608  0.16669908  0.16612695]


(50, 6, 100)
attention = [[ 0.1667901   0.16582307  0.16546658  0.16683553  0.16784075  0.167244  ]
 [ 0.16676316  0.16678005  0.16654173  0.16705532  0.16686849  0.16599125]
 [ 0.16804986  0.16570501  0.16670801  0.16506091  0.1667669   0.16770937]
 [ 0.16754442  0.16592358  0.16667157  0.16590145  0.16664062  0.1673183 ]
 [ 0.16737361  0.16603176  0.16663505  0.16697119  0.16687347  0.16611496]
 [ 0.16699587  0.16633564  0.16627234  0.16706915  0.16677795  0.16654909]
 [ 0.16750963  0.16596989  0.16642286  0.16676506  0.16616969  0.1671629 ]
 [ 0.16716199  0.16663145  0.16690193  0.16662842  0.16600938  0.16666681]
 [ 0.16706935  0.16588476  0.16585873  0.16686562  0.16733025  0.16699135]
 [ 0.16678531  0.16644442  0.16596405  0.1669106   0.16687241  0.16702326]
 [ 0.16789103  0.16526993  0.16530597  0.16624874  0.16751029  0.16777405]
 [ 0.16685554  0.16636999  0.16596508  0.16676317  0.16733144  0.16671473]
 [ 0.16679794  0.16659321  0.16622613  0.16675043  0.16706215  0.16657019]


(50, 6, 100)
attention = [[ 0.1671847   0.16617569  0.16611983  0.16691925  0.16701213  0.16658844]
 [ 0.16690147  0.16646788  0.16634069  0.1665118   0.1669389   0.16683918]
 [ 0.16645287  0.16690582  0.16664843  0.16726393  0.16639771  0.16633137]
 [ 0.16674308  0.16648838  0.16608475  0.16677769  0.16686282  0.16704334]
 [ 0.16713491  0.16608123  0.16597436  0.16730803  0.16730255  0.16619898]
 [ 0.16654047  0.1665839   0.16617931  0.16709152  0.16691376  0.16669096]
 [ 0.16730948  0.16632682  0.16627502  0.16642886  0.16707586  0.16658382]
 [ 0.16670001  0.16682605  0.16670023  0.16680586  0.16626501  0.16670288]
 [ 0.16708754  0.16659845  0.16691768  0.16637525  0.16627339  0.16674763]
 [ 0.16720146  0.16617462  0.16620739  0.16679019  0.16716594  0.16646031]
 [ 0.16766867  0.16573551  0.16676275  0.16631183  0.16640574  0.1671156 ]
 [ 0.16662447  0.16681537  0.16627726  0.16680893  0.16685437  0.16661964]
 [ 0.16715764  0.16651386  0.16677886  0.166775    0.16589306  0.16688156]


(50, 6, 100)
attention = [[ 0.16716199  0.16663145  0.16690193  0.16662842  0.16600938  0.16666681]
 [ 0.16747977  0.1662401   0.16680345  0.16579041  0.16767183  0.16601439]
 [ 0.16751274  0.16595711  0.16634251  0.1660976   0.16682228  0.16726781]
 [ 0.16719647  0.16644309  0.16654545  0.16667205  0.16629142  0.16685152]
 [ 0.1668022   0.16652279  0.16624574  0.16714975  0.16687727  0.16640222]
 [ 0.16676088  0.16657373  0.16649337  0.16674136  0.16683508  0.16659559]
 [ 0.16734861  0.16623047  0.16713047  0.16611284  0.16623272  0.16694486]
 [ 0.16708292  0.16629294  0.16584991  0.16674578  0.16721578  0.16681267]
 [ 0.16698053  0.16655888  0.1673011   0.16697493  0.16581531  0.16636924]
 [ 0.16662665  0.1669118   0.16642739  0.16705132  0.16696309  0.16601978]
 [ 0.16671741  0.16704008  0.16752976  0.16690893  0.16546197  0.1663419 ]
 [ 0.16725211  0.16634582  0.16673733  0.16642739  0.16658872  0.16664875]
 [ 0.16766053  0.16611397  0.16673782  0.16613655  0.16717762  0.16617358]


(50, 6, 100)
attention = [[ 0.16777636  0.16572721  0.16637243  0.16681431  0.16638659  0.16692309]
 [ 0.16696011  0.166723    0.1666608   0.16697222  0.16598645  0.16669746]
 [ 0.16738163  0.16608828  0.16621733  0.16611366  0.16688982  0.16730922]
 [ 0.16695745  0.16667463  0.16667727  0.16672787  0.16656207  0.1664007 ]
 [ 0.16688552  0.16656603  0.16714846  0.16647005  0.16624194  0.16668808]
 [ 0.16730846  0.16602148  0.16592419  0.16673021  0.1678161   0.16619949]
 [ 0.16662447  0.16681537  0.16627726  0.16680893  0.16685437  0.16661964]
 [ 0.16668111  0.16694711  0.1669139   0.16723768  0.16612218  0.16609798]
 [ 0.16637899  0.16710567  0.16672285  0.16721521  0.16652673  0.16605045]
 [ 0.16673613  0.16695736  0.16673243  0.1666458   0.16598588  0.1669424 ]
 [ 0.16735913  0.165878    0.16617134  0.16675478  0.1669101   0.16692673]
 [ 0.16710746  0.16665533  0.16711235  0.16616854  0.16591172  0.16704457]
 [ 0.16681296  0.16652611  0.16636489  0.16674136  0.16670157  0.16685314]


(50, 6, 100)
attention = [[ 0.16609159  0.16708897  0.16606653  0.16747807  0.16685867  0.16641615]
 [ 0.16745961  0.16647439  0.16702436  0.16651466  0.16520372  0.16732326]
 [ 0.1667157   0.16668183  0.16655838  0.16698447  0.16662085  0.16643879]
 [ 0.16709033  0.16625509  0.16618389  0.16651401  0.16714002  0.16681658]
 [ 0.16669619  0.16710426  0.16670395  0.16691421  0.16634007  0.16624132]
 [ 0.16726492  0.16645628  0.16700105  0.1666027   0.16621642  0.16645862]
 [ 0.16675024  0.16698191  0.16724561  0.16672811  0.16615446  0.16613965]
 [ 0.16747354  0.16580236  0.16613723  0.16614152  0.16696766  0.16747753]
 [ 0.16739587  0.16568738  0.16565037  0.16701932  0.16820265  0.16604444]
 [ 0.16672777  0.16640659  0.16619684  0.166912    0.16707163  0.16668512]
 [ 0.16722316  0.16653764  0.16680175  0.16655737  0.16634758  0.16653247]
 [ 0.16735007  0.1664473   0.16670944  0.16645485  0.16625889  0.16677932]
 [ 0.16723789  0.16626696  0.16665794  0.16721179  0.16664606  0.1659794 ]


(50, 6, 100)
attention = [[ 0.16747275  0.16621149  0.16640337  0.16636761  0.16689183  0.16665298]
 [ 0.1673203   0.16644983  0.16689613  0.16638947  0.16648175  0.16646254]
 [ 0.16682625  0.16633433  0.16597597  0.16676117  0.16758536  0.1665169 ]
 [ 0.16753088  0.16621698  0.16686162  0.16639462  0.16679634  0.16619949]
 [ 0.16726492  0.16645628  0.16700105  0.1666027   0.16621642  0.16645862]
 [ 0.16715559  0.16645144  0.16675322  0.16625269  0.16662741  0.16675963]
 [ 0.16682586  0.16670443  0.16657032  0.16697857  0.1664792   0.16644169]
 [ 0.16830172  0.16545336  0.16710514  0.16533914  0.16637005  0.16743065]
 [ 0.1671847   0.16617569  0.16611983  0.16691925  0.16701213  0.16658844]
 [ 0.16763353  0.16606353  0.16677673  0.16644119  0.16663291  0.16645201]
 [ 0.16743326  0.16625541  0.16692659  0.16628428  0.16636558  0.16673496]
 [ 0.16646771  0.16702522  0.16642638  0.16721924  0.16675194  0.1661095 ]
 [ 0.16759005  0.16568536  0.16618308  0.16619349  0.16806507  0.16628291]


(50, 6, 100)
attention = [[ 0.16637252  0.16696003  0.16679864  0.16722257  0.16624446  0.16640177]
 [ 0.16713832  0.16650091  0.16650437  0.16683431  0.1666345   0.16638756]
 [ 0.16730984  0.16647552  0.1666708   0.16696087  0.16688886  0.1656941 ]
 [ 0.16663468  0.16648756  0.1663738   0.16674022  0.16700836  0.16675527]
 [ 0.16668111  0.16694711  0.1669139   0.16723768  0.16612218  0.16609798]
 [ 0.16754904  0.16630518  0.16721509  0.16585304  0.16592282  0.16715486]
 [ 0.16750807  0.16623543  0.16682251  0.16582538  0.16660126  0.16700739]
 [ 0.16705287  0.16641873  0.16669945  0.16619022  0.16658163  0.16705711]
 [ 0.16741543  0.16617092  0.16665545  0.16700815  0.16665423  0.16609582]
 [ 0.16699135  0.16629882  0.16641277  0.16684398  0.16681601  0.166637  ]
 [ 0.16735913  0.165878    0.16617134  0.16675478  0.1669101   0.16692673]
 [ 0.16735277  0.1665137   0.16730772  0.16595663  0.16604346  0.16682573]
 [ 0.16651624  0.16701569  0.16678458  0.16680361  0.16643339  0.16644655]


(50, 6, 100)
attention = [[ 0.16734448  0.16585343  0.16622047  0.16739388  0.1664196   0.16676807]
 [ 0.16670929  0.16640213  0.1658069   0.16675575  0.16724429  0.16708165]
 [ 0.16685863  0.16641946  0.16634916  0.1670616   0.16701254  0.16629861]
 [ 0.16704915  0.16623056  0.16647816  0.16704205  0.16680743  0.16639259]
 [ 0.16741629  0.166411    0.16679803  0.16662998  0.16614923  0.16659546]
 [ 0.16650161  0.16678551  0.16650648  0.1672176   0.16673598  0.1662527 ]
 [ 0.16677551  0.16693865  0.16686966  0.16675961  0.16604909  0.16660756]
 [ 0.16690692  0.16677074  0.16649111  0.1663516   0.16654405  0.16693552]
 [ 0.16710255  0.16619696  0.1658317   0.16692171  0.16772822  0.16621889]
 [ 0.16784334  0.16611966  0.16745806  0.16638122  0.16571049  0.16648728]
 [ 0.16734761  0.16631135  0.16707708  0.16664037  0.16613577  0.16648777]
 [ 0.16693939  0.16671807  0.1670167   0.16630705  0.16595969  0.16705899]
 [ 0.1665986   0.16674162  0.1665644   0.16647863  0.16718359  0.16643313]


(50, 6, 100)
attention = [[ 0.16709441  0.1662702   0.16644444  0.16652964  0.1667968   0.16686448]
 [ 0.16738982  0.16611439  0.16622898  0.16688164  0.16615404  0.1672311 ]
 [ 0.1669936   0.16620506  0.16591828  0.16716431  0.16714022  0.16657862]
 [ 0.16713832  0.16650091  0.16650437  0.16683431  0.1666345   0.16638756]
 [ 0.16755773  0.16576377  0.16596299  0.16659963  0.16783583  0.16628009]
 [ 0.16730756  0.166214    0.16692366  0.16607821  0.16608784  0.16738871]
 [ 0.16684939  0.16672932  0.16662773  0.16669373  0.16646975  0.16663007]
 [ 0.16735931  0.1663534   0.1671567   0.166446    0.16588527  0.16679925]
 [ 0.16742645  0.1660808   0.16654864  0.16627283  0.16665484  0.16701649]
 [ 0.16710438  0.16681826  0.16711576  0.16578007  0.16641846  0.1667631 ]
 [ 0.16700146  0.1665165   0.16655597  0.16702439  0.16678198  0.16611971]
 [ 0.16682817  0.16638567  0.16602068  0.16781132  0.16734415  0.16561002]
 [ 0.16688482  0.16669513  0.16678099  0.16627194  0.16644551  0.16692157]


(50, 6, 100)
attention = [[ 0.16686785  0.16683128  0.1674666   0.16729854  0.16547996  0.16605572]
 [ 0.16762732  0.16584314  0.16675766  0.16671963  0.16673055  0.16632175]
 [ 0.16721322  0.1664753   0.16653293  0.16631833  0.16614401  0.16731621]
 [ 0.16720608  0.16640314  0.16688938  0.16631147  0.16639841  0.16679145]
 [ 0.16709286  0.16654928  0.16684049  0.16633052  0.16639541  0.16679148]
 [ 0.16714551  0.16635174  0.1665144   0.16641465  0.16679682  0.16677687]
 [ 0.16688366  0.16684641  0.16717558  0.16609688  0.16619344  0.16680393]
 [ 0.16711569  0.16633788  0.16607521  0.16622187  0.16689627  0.16735315]
 [ 0.16738692  0.16624342  0.16683707  0.16653469  0.16626965  0.16672824]
 [ 0.16716635  0.16645677  0.16641618  0.1667874   0.16713932  0.16603403]
 [ 0.16692764  0.16634095  0.16664118  0.16646972  0.16661111  0.16700928]
 [ 0.16694357  0.16663928  0.16682762  0.16647933  0.16622873  0.16688144]
 [ 0.16715777  0.16648471  0.166633    0.16647997  0.16660355  0.16664109]


(50, 6, 100)
attention = [[ 0.1669157   0.16635644  0.16653568  0.16685334  0.16675629  0.1665826 ]
 [ 0.16754727  0.16565706  0.16649878  0.16596742  0.16739646  0.1669331 ]
 [ 0.16693068  0.16650032  0.16672425  0.16704017  0.16654898  0.16625561]
 [ 0.16674341  0.16670756  0.16675343  0.16704915  0.16597848  0.16676812]
 [ 0.16710028  0.16657449  0.16678327  0.16654578  0.16630329  0.16669288]
 [ 0.16765371  0.16618992  0.16726208  0.16617694  0.16588505  0.1668323 ]
 [ 0.16652216  0.16654977  0.16628376  0.16710433  0.16732599  0.166214  ]
 [ 0.16720608  0.16640314  0.16688938  0.16631147  0.16639841  0.16679145]
 [ 0.16688552  0.16656603  0.16714846  0.16647005  0.16624194  0.16668808]
 [ 0.1673893   0.166004    0.16670799  0.16588795  0.16665174  0.16735896]
 [ 0.1665986   0.16674162  0.1665644   0.16647863  0.16718359  0.16643313]
 [ 0.16701643  0.1663667   0.16663     0.16675778  0.16704722  0.16618182]
 [ 0.16730213  0.16602844  0.16630465  0.16677026  0.16698435  0.16661026]


(50, 6, 100)
attention = [[ 0.16705287  0.16641873  0.16669945  0.16619022  0.16658163  0.16705711]
 [ 0.16684988  0.16630964  0.16608633  0.16681212  0.16705227  0.16688982]
 [ 0.16716635  0.16645677  0.16641618  0.1667874   0.16713932  0.16603403]
 [ 0.16686016  0.16634187  0.16648561  0.16703893  0.16632712  0.16694629]
 [ 0.16738662  0.16629271  0.16678748  0.16676268  0.16638899  0.16638154]
 [ 0.16687331  0.166465    0.16633734  0.16693376  0.16684896  0.1665417 ]
 [ 0.16650161  0.16678551  0.16650648  0.1672176   0.16673598  0.1662527 ]
 [ 0.16668469  0.16683301  0.16685277  0.16664796  0.16623762  0.16674401]
 [ 0.16769457  0.16587876  0.16648842  0.16612875  0.16630277  0.16750674]
 [ 0.16684939  0.16672932  0.16662773  0.16669373  0.16646975  0.16663007]
 [ 0.16744766  0.16630049  0.16701809  0.16640498  0.16640368  0.16642511]
 [ 0.16695486  0.16627872  0.1665712   0.16637141  0.16673879  0.16708508]
 [ 0.16702002  0.16655882  0.1668033   0.16647647  0.16639549  0.16674595]


(50, 6, 100)
attention = [[ 0.1673893   0.166004    0.16670799  0.16588795  0.16665174  0.16735896]
 [ 0.16672182  0.16684477  0.16669595  0.16603135  0.16645882  0.16724731]
 [ 0.16716303  0.16647297  0.16671704  0.16662502  0.16666768  0.16635427]
 [ 0.16707857  0.16625343  0.16613661  0.16648659  0.16709381  0.16695096]
 [ 0.16675147  0.16660692  0.16654435  0.16734956  0.1667088   0.16603874]
 [ 0.16707633  0.16651857  0.1665483   0.16652985  0.16655982  0.16676717]
 [ 0.16695301  0.16641596  0.16638201  0.16669826  0.16639262  0.16715817]
 [ 0.16676487  0.16682106  0.1667795   0.16691385  0.16583794  0.16688274]
 [ 0.16698438  0.16679737  0.16691567  0.16672297  0.1662569   0.16632286]
 [ 0.16711882  0.16654807  0.16667911  0.16657275  0.16691698  0.16616428]
 [ 0.16728453  0.16628817  0.16679348  0.16624579  0.16648747  0.16690059]
 [ 0.16695745  0.16667463  0.16667727  0.16672787  0.16656207  0.1664007 ]
 [ 0.16650991  0.16696002  0.167108    0.16740444  0.16648717  0.1655305 ]


(50, 6, 100)
attention = [[ 0.16710255  0.16619696  0.1658317   0.16692171  0.16772822  0.16621889]
 [ 0.16664405  0.16646966  0.16635759  0.16711494  0.16686819  0.16654564]
 [ 0.16784334  0.16611966  0.16745806  0.16638122  0.16571049  0.16648728]
 [ 0.16711658  0.16608877  0.16626549  0.16687675  0.16651224  0.16714022]
 [ 0.16725515  0.16660863  0.16714355  0.16598313  0.16617484  0.16683476]
 [ 0.16733584  0.16624545  0.16668493  0.16645487  0.16646793  0.16681091]
 [ 0.16750807  0.16623543  0.16682251  0.16582538  0.16660126  0.16700739]
 [ 0.16746794  0.16592176  0.16626671  0.16632895  0.16722888  0.16678579]
 [ 0.16699523  0.16613708  0.16631404  0.16695568  0.16658787  0.16701016]
 [ 0.1672855   0.166161    0.1656391   0.16674042  0.16761026  0.16656373]
 [ 0.16748217  0.16570188  0.16598046  0.16652374  0.16717538  0.16713631]
 [ 0.16726585  0.16613232  0.16608512  0.16719097  0.16748472  0.16584088]
 [ 0.16669157  0.16676569  0.16636449  0.16684265  0.16704905  0.16628651]


(50, 6, 100)
attention = [[ 0.16690969  0.16642974  0.16622144  0.16692966  0.1672385   0.16627093]
 [ 0.16712879  0.16671765  0.16668612  0.1659354   0.16636196  0.16717003]
 [ 0.16699772  0.16580532  0.16502038  0.16656923  0.16800459  0.16760284]
 [ 0.16763252  0.16582684  0.16619405  0.16670002  0.16711792  0.16652869]
 [ 0.16661105  0.16680636  0.16635492  0.16726896  0.16704293  0.16591577]
 [ 0.166922    0.16651399  0.16606322  0.1673646   0.16669564  0.1664407 ]
 [ 0.16795021  0.16559476  0.16646704  0.16592668  0.16748607  0.16657528]
 [ 0.16705661  0.16633299  0.16666794  0.16642159  0.16688783  0.16663307]
 [ 0.16678511  0.1667757   0.16675876  0.16666514  0.16586421  0.16715105]
 [ 0.16721411  0.16727167  0.16656312  0.16662094  0.1660625   0.16626766]
 [ 0.16655655  0.16700906  0.16662019  0.16684097  0.16648887  0.1664843 ]
 [ 0.16715764  0.16651386  0.16677886  0.166775    0.16589306  0.16688156]
 [ 0.16741762  0.16574702  0.16603066  0.16642211  0.16714334  0.16723926]


(50, 6, 100)
attention = [[ 0.16716373  0.16637062  0.16671894  0.1667984   0.16655724  0.16639104]
 [ 0.16687672  0.16678256  0.16703197  0.16655348  0.16646011  0.16629511]
 [ 0.16686447  0.16639288  0.16638212  0.16641971  0.16696629  0.16697456]
 [ 0.16685812  0.16695511  0.16693549  0.16660267  0.16638061  0.16626802]
 [ 0.16714551  0.16635174  0.1665144   0.16641465  0.16679682  0.16677687]
 [ 0.16755112  0.16592766  0.16640741  0.16644354  0.16670157  0.16696869]
 [ 0.16709062  0.16615471  0.16629267  0.16663735  0.16685665  0.16696799]
 [ 0.16690017  0.16663647  0.16653031  0.16640039  0.16649589  0.16703694]
 [ 0.16727777  0.16632028  0.16686979  0.16660058  0.16631827  0.1666133 ]
 [ 0.16739622  0.16613409  0.16670151  0.16598393  0.16666766  0.16711658]
 [ 0.1675794   0.16583224  0.16614528  0.16604125  0.16712876  0.167273  ]
 [ 0.16671295  0.16652599  0.16597387  0.16652834  0.16724721  0.16701154]
 [ 0.16690934  0.16647618  0.1664595   0.16684102  0.1666479   0.16666608]


(50, 6, 100)
attention = [[ 0.16747436  0.16608192  0.16690466  0.16625874  0.1666268   0.16665354]
 [ 0.16729772  0.16613702  0.16607986  0.16680922  0.16758984  0.16608632]
 [ 0.16758774  0.16599274  0.16660061  0.16651031  0.16636051  0.16694811]
 [ 0.16609159  0.16708897  0.16606653  0.16747807  0.16685867  0.16641615]
 [ 0.16663341  0.16692217  0.16648734  0.16728607  0.16657673  0.16609432]
 [ 0.16797385  0.16605793  0.16710722  0.16553038  0.16592988  0.16740085]
 [ 0.16663496  0.16665307  0.16664593  0.16670786  0.1668101   0.1665481 ]
 [ 0.16668469  0.16683301  0.16685277  0.16664796  0.16623762  0.16674401]
 [ 0.16794892  0.16611351  0.1675705   0.16585098  0.16524592  0.16727018]
 [ 0.16672182  0.16684477  0.16669595  0.16603135  0.16645882  0.16724731]
 [ 0.16693212  0.16611619  0.16607821  0.16687252  0.16760792  0.16639294]
 [ 0.16706841  0.16615975  0.16576278  0.16644207  0.16723986  0.16732714]
 [ 0.16670485  0.16674732  0.16607787  0.16707128  0.16652469  0.16687398]


(50, 6, 100)
attention = [[ 0.16708462  0.16589993  0.16582477  0.16693252  0.16779704  0.16646113]
 [ 0.16718982  0.16618954  0.16632359  0.16677582  0.1671394   0.16638178]
 [ 0.16635466  0.16659056  0.16579801  0.16770913  0.16767599  0.16587168]
 [ 0.1666297   0.16688988  0.16658483  0.16698864  0.16643502  0.16647187]
 [ 0.16738456  0.16627108  0.16663577  0.16611643  0.16647324  0.16711883]
 [ 0.16822864  0.16556726  0.16662169  0.16629526  0.1653285   0.16795866]
 [ 0.16696677  0.16658457  0.1666408   0.16691169  0.16649418  0.16640204]
 [ 0.16699204  0.16638847  0.16646767  0.16700907  0.16634017  0.16680261]
 [ 0.16791268  0.16567141  0.16643327  0.16661867  0.16693124  0.16643274]
 [ 0.16693768  0.1667155   0.16699579  0.16633686  0.16640733  0.16660689]
 [ 0.16696011  0.166723    0.1666608   0.16697222  0.16598645  0.16669746]
 [ 0.16717924  0.16631514  0.16657208  0.16629171  0.16633411  0.16730772]
 [ 0.16652216  0.16654977  0.16628376  0.16710433  0.16732599  0.166214  ]


(50, 6, 100)
attention = [[ 0.16686359  0.16654241  0.16646026  0.16668777  0.16674055  0.1667054 ]
 [ 0.16685303  0.16665886  0.16650586  0.16641174  0.16669615  0.16687432]
 [ 0.16723107  0.16612332  0.16648538  0.16611801  0.16683768  0.16720457]
 [ 0.16739587  0.16568738  0.16565037  0.16701932  0.16820265  0.16604444]
 [ 0.16710947  0.1664218   0.16686778  0.16665266  0.16619903  0.1667493 ]
 [ 0.1663539   0.16729945  0.16684812  0.1668324   0.16635369  0.16631261]
 [ 0.16686785  0.16683128  0.1674666   0.16729854  0.16547996  0.16605572]
 [ 0.16669619  0.16710426  0.16670395  0.16691421  0.16634007  0.16624132]
 [ 0.16686359  0.16654241  0.16646026  0.16668777  0.16674055  0.1667054 ]
 [ 0.16648458  0.16704364  0.16714248  0.16668254  0.16612123  0.16652545]
 [ 0.16727322  0.16637026  0.16695838  0.16622509  0.16644089  0.16673224]
 [ 0.1667202   0.16704601  0.16735858  0.16682725  0.16619323  0.16585478]
 [ 0.16713491  0.16608123  0.16597436  0.16730803  0.16730255  0.16619898]


(50, 6, 100)
attention = [[ 0.16639119  0.16658771  0.16563547  0.16690418  0.16797556  0.16650601]
 [ 0.16694894  0.16633976  0.16642644  0.16687146  0.16636227  0.16705114]
 [ 0.16686386  0.16680808  0.16729827  0.16674533  0.16597448  0.16631006]
 [ 0.16695222  0.16685599  0.16680574  0.16688034  0.16571704  0.16678867]
 [ 0.16750807  0.16623543  0.16682251  0.16582538  0.16660126  0.16700739]
 [ 0.16716765  0.16652276  0.16659741  0.16614605  0.16660643  0.16695972]
 [ 0.16696982  0.1662481   0.16672741  0.16781689  0.16670161  0.1655362 ]
 [ 0.16692589  0.16670504  0.16661993  0.16636537  0.16631296  0.16707073]
 [ 0.16704252  0.16655377  0.16675971  0.16655274  0.16662087  0.16647047]
 [ 0.16762732  0.16584314  0.16675766  0.16671963  0.16673055  0.16632175]
 [ 0.16702127  0.16616841  0.16591267  0.16697183  0.16667946  0.1672464 ]
 [ 0.16705726  0.16668682  0.16688211  0.16648266  0.16598496  0.16690621]
 [ 0.16747609  0.16632971  0.16710953  0.16615805  0.16649641  0.16643018]


(50, 6, 100)
attention = [[ 0.16713789  0.16622719  0.16649823  0.16678004  0.16673945  0.16661721]
 [ 0.16746794  0.16592176  0.16626671  0.16632895  0.16722888  0.16678579]
 [ 0.16760628  0.16597645  0.16656291  0.16665298  0.16676119  0.16644029]
 [ 0.1669554   0.16680133  0.16690744  0.16659839  0.16660658  0.16613089]
 [ 0.16777636  0.16572721  0.16637243  0.16681431  0.16638659  0.16692309]
 [ 0.16713789  0.16622719  0.16649823  0.16678004  0.16673945  0.16661721]
 [ 0.16730356  0.16631377  0.166601    0.16627583  0.16644594  0.16705991]
 [ 0.16714153  0.16631383  0.1661503   0.16685338  0.16676612  0.16677488]
 [ 0.1669798   0.16622038  0.16626659  0.16635507  0.16747421  0.16670388]
 [ 0.16687672  0.16678256  0.16703197  0.16655348  0.16646011  0.16629511]
 [ 0.16700913  0.16629909  0.16629496  0.16659121  0.16677603  0.16702959]
 [ 0.16820215  0.16550337  0.16675811  0.16596967  0.16640574  0.16716091]
 [ 0.16678531  0.16644442  0.16596405  0.1669106   0.16687241  0.16702326]


 50/369 [===>..........................] - ETA: 0s
Test loss / test accuracy = 0.6927 / 0.6070
